INSERT INTO `migrations` VALUES ('20170904211126'); 

-- Texts for database scripts for Are We There Yeti 3
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007029, 'Ahhhh!!! What is that thing?!', '으아아악!!! 저게 뭐지?', 'Ahhhh ! Qu’est-ce que c’est ?!', 'Ahhhh!!! Was ist das denn?!', '啊！！！那是什么东西？！', '啊!!!那是什麼東西?!', '¡¡¡Ahhhh!!! ¡¿Qué es eso?!', '¡¡¡Ahhhh!!! ¡¿Qué es eso?!', 'А-а-а-а!!! Что это?!');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007030, 'Umi sent you, didn\'t she?! She told me to expect a surprise, but I never thought that this is what she meant!', '우미가 보낸 거 맞죠? 평소에 절 깜짝 놀라게 해 주겠다고 말했지만, 이런 것일 줄은 생각도 못 했어요!', 'Umi vous envoie, n’est-ce pas ? Elle m’a dit de m’attendre à une surprise, mais je n’aurais jamais cru que c’était de cela dont elle parlait !', 'Umi hat Euch geschickt, oder? Sie hat mir gesagt, ich solle mich auf eine Überraschung gefasst machen, aber ich hatte keine Ahnung, dass sie das gemeint hat!', '乌米派你来的，是吗？！她告诉我会有一个惊喜，但是我从没想到她是这个意思！', '烏米派你來的，是嗎?!她告訴我會有一個驚喜，但是我從沒想到她是這個意思!', '¡Umi te ha enviado, ¿verdad?! Me dijo que esperara una sorpresa, ¡pero nunca pensé que se refiriera a esto!', '¡Umi te ha enviado, ¿verdad?! Me dijo que esperara una sorpresa, ¡pero nunca pensé que se refiriera a esto!', 'Так тебя Уми прислала, да?! Она обещала мне сюрприз, но я бы в жизни не подумала, что он будет таким!');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007031, 'Ahhhhh!!!', '으아아악!!!', 'Ahhhhh !', 'Aaaahhh!', '啊！！！', '啊!!!', '¡¡¡Ahhhhh!!!', '¡¡¡Ahhhhh!!!', 'Аххххх!!!');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007032, 'You big meanie! Who put you up to this?', '어떻게 이럴 수가 있죠! 누가 이런 짓을 시킨 거예요?', 'Ah, vous alors ! Qui vous a dit de faire ça ?', 'Das ist gemein! Wer hat Euch dazu angestiftet?', '你个尖酸的刻薄鬼！谁把这个给你的？', '你個尖酸的刻薄鬼!誰把這個給你的?', '¡Eh, tacaño! ¿Quién te dio la idea?', '¡Eh, tacaño! ¿Quién te dio la idea?', 'Ах ты, $gнегодяй:негодяйка;! Кто тебя на это подбил?');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007033, 'It was Umi, wasn\'t it?! She\'s always playing jokes on me, and now she\'s got you in on it too!', '우미가 시킨 거죠? 항상 나한테 장난을 치더니, 이제는 당신까지 끌어들였군요!', 'C’est Umi, n’est-ce pas ? Elle ne cesse de me jouer des tours et maintenant vous vous y mettez aussi !', 'Bestimmt Umi, oder? Die spielt mir ständig irgendwelche Streiche, und jetzt hat sie auch noch Euch mit eingespannt!', '是乌米，是吗？？她总是跟我开玩笑，现在也让你参与到玩笑之中了！', '是烏米，是嗎??她總是跟我開玩笑，現在也讓你參與到玩笑之中了!', '¡Fue Umi, ¿verdad?! Siempre me está gastando bromas, ¡y ahora también te la ha jugado a ti!', '¡Fue Umi, ¿verdad?! Siempre me está gastando bromas, ¡y ahora también te la ha jugado a ti!', 'Это была Уми, да?! Она постоянно разыгрывает меня, а теперь вот и до тебя добралась!');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007034, '%s sighs.', '%s|1이;가; 한숨을 쉽니다.', '%s soupire.', '%s seufzt.', '%s叹了口气。', '%s嘆了一口氣。', '%s suspira.', '%s suspira.', '%s вздыхает.');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007035, '%s runs quickly away from Umi\'s Mechanical Yeti.', '%s|1이;가; 재빨리 우미의 기계설인으로부터 멀리 달아납니다.', '%s s\'enfuit à toute vitesse devant le yéti mécanique d\'Umi.', '%s läuft schnell vor Umis mechanischem Yeti weg.', '%s迅速从乌米的机械雪人面前逃跑。', '%s迅速逃離烏米的機械雪人。', '%s huye corriendo del yeti mecánico de Umi.', '%s huye corriendo del yeti mecánico de Umi.', '%s стремглав убегает от механического йети Уми.');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007036, 'Why do you chase me, Mechanical Yeti?! WHY?!', '기계설인아, 왜 날 쫓아오는 거니? 도대체 왜?', 'Pourquoi me chasses-tu, yéti mécanique, hein ? POURQUOI ?', 'Warum verfolgst du mich, mechanischer Yeti?! WARUM?!', '你为什么要追我，机械雪人？！为什么？！', '你為什麼要追我，機械雪人?!為什麼?!', '¡¿Por qué me persigues, yeti mecánico?! ¡¿POR QUÉ?!', '¡¿Por qué me persigues, yeti mecánico?! ¡¿POR QUÉ?!', 'Почему ты гонишься за мной, механический йети? ПОЧЕМУ?!');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007037, '%s looks relieved.', '%s|1이;가; 안심한 것 같습니다.', '%s semble soulagé.', '%s sieht erleichtert aus.', '%s看上去很轻松。', '%s看起來鬆了一口氣。', '%s mira con alivio.', '%s mira con alivio.', '%s выглядит успокоенным.');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000007038, 'I\'m jumpy as it is... and people insist on scaring me... Next time, though, I\'ll be ready!', '그렇지 않아도 심장이 약한 편이라 잘 놀라는데... 자꾸만 놀라게 하는군... 하지만 다음번에는 단단히 준비하고 있을 거야!', 'Je suis impressionnable, et les gens s\'amusent à me faire sursauter... Mais la prochaine fois, je ne me laisserai pas faire !', 'Ich bin doch ohnehin schon schreckhaft genug... und trotzdem wollen mich die Leute dauernd erschrecken... Aber beim nächsten Mal bin ich vorbereitet!', '我总是战战兢兢……人们还在不断吓我……但是下次，我会有所准备的！', '我總是戰戰兢兢...人們還在不斷嚇我...但是下次，我會有所準備的!', 'Yo siempre estoy de los nervios... y la gente se empeña en asustarme... ¡Pero la próxima vez estaré preparado!', 'Yo siempre estoy de los nervios... y la gente se empeña en asustarme... ¡Pero la próxima vez estaré preparado!', 'Я ужасно нервный... и всем нравится меня пугать... Но в следующий раз я буду готов!');

-- Texts for core scripts for Are We There Yeti 3
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1900169, '%s marches around, roaring and making a ruckus.', '%s|1이;가; 이리저리 돌아다니면서 큰 소리를 내고 소동을 피웁니다.', '%s marche en rond, en rugissant et en faisant du grabuge.', '%s marschiert herum, brüllt und macht Rabatz.', '%s到处乱跑，大声喊叫，制造骚乱。', '%s到處亂跑，大聲喊叫，製造騷亂。', '%s camina con paso firme, haciendo ruido y armando jaleo.', '%s camina con paso firme, haciendo ruido y armando jaleo.', '%s ходит кругами, ревет и шумит.', 0, 2, 0, 0, 'Umi\'s Mechanical Yeti - Emote on spawn.');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1900170, 'RAAAAAAAR!', '우워어어어어!', 'RAAAAAAAR !', 'RAAAAAAAR!', '啊啊啊啊啊啊！', '啊啊啊啊啊啊!', '¡RAAAAAAAR!', '¡RAAAAAAAR!', 'РРРРЫЫЫЫЫ!!!', 0, 0, 0, 0, 'Umi\'s Mechanical Yeti - Say on spawn.');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1900171, 'Oh!!! Get that thing away from me!', '으악!!! 제발 저것 좀 떨어뜨려 줘!', 'Oh !!! Je ne veux pas voir cette chose !', 'Oh!!! Nehmt das Ding da weg!', '啊呀！把那东西从我这儿拿走！', '啊呀!把那東西從我這兒拿走!', '¡¡¡Oh!!! ¡Aleja esa cosa de mí!', '¡¡¡Oh!!! ¡Aleja esa cosa de mí!', 'А-а-а! Уберите это от меня!', 0, 0, 0, 0, 'Quixxil - Say on Umi\'s Mechanical Yeti spawn.');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1900172, '%s jumps in fright!', '%s|1이;가; 무서워하며 흠칫 놀랍니다!', '%s sursaute d’effroi !', '%s zuckt erschreckt zusammen.', '%s惊骇地跳起来！', '%s驚駭地跳起來!', '%s salta del susto.', '%s salta del susto.', '%s подпрыгивает от испуга!', 0, 2, 0, 0, 'Sprinkle - Emote on Umi\'s Mechanical Yeti spawn.');
INSERT INTO `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES (-1900173, '%s jumps in fright!', '%s|1이;가; 무서워서 팔짝 뜁니다!', '%s sursaute d’effroi !', '%s zuckt erschreckt zusammen.', '%s惊骇地跳起来！', '%s驚駭地跳起來!', '%s salta del susto.', '%s salta del susto.', '%s подпрыгивает от испуга!', 0, 2, 0, 0, 'Legacki - Emote on Umi\'s Mechanical Yeti spawn.');

-- Waypoint scripts for Are We There Yeti 3
DELETE FROM `creature_movement_scripts` WHERE `id` IN (302, 303, 304, 305, 306, 307, 308);
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (302, 1, 0, 0, 0, 0, 0, 0, 2000007029, 0, 0, 0, 0, 0, 0, 0, 'Sprinkle - Say Text 1');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (303, 0, 15, 17163, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Sprinkle - Cast Unsummon Mechanical Yeti');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (304, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Sprinkle - Stop Waypoint Movement');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (304, 1, 0, 0, 0, 0, 0, 0, 2000007030, 0, 0, 0, 0, 0, 0, 0, 'Sprinkle - Say Text 2');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (304, 1, 35, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.9968, 'Sprinkle - Reset Orientation');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (305, 0, 0, 2, 0, 0, 0, 0, 2000007035, 0, 0, 0, 0, 0, 0, 0, 'Quixxil - Say Emote Text 1');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (306, 0, 15, 17163, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Quixxil - Cast Unsummon Mechanical Yeti');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (306, 1, 0, 2, 0, 0, 0, 0, 2000007037, 0, 0, 0, 0, 0, 0, 0, 'Quixxil - Say Emote Text 2');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (307, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Quixxil - Stop Waypoint Movement');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (307, 1, 35, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.43314, 'Quixxil - Reset Orientation');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (307, 1, 0, 0, 0, 0, 0, 0, 2000007038, 0, 0, 0, 0, 0, 0, 0, 'Quixxil - Say Text 3');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (308, 0, 0, 0, 0, 0, 0, 0, 2000007032, 0, 0, 0, 0, 0, 0, 0, 'Legacki - Say Text 1');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (308, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Legacki - Stop Waypoint Movement');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (308, 1, 35, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.436332, 'Legacki - Reset Orientation');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (308, 4, 0, 0, 0, 0, 0, 0, 2000007033, 0, 0, 0, 0, 0, 0, 0, 'Legacki - Say Text 2');

-- Waypoints for Sprinkle
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 1, -7111.11, -3741.78, 8.60926, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.9968, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 2, -7111.19, -3746.24, 8.373, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 3, -7109.22, -3754.29, 8.372, 500, 302, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 4, -7109.13, -3762.04, 8.373, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 5, -7114.15, -3811.19, 8.39081, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 6, -7155.4, -3820.39, 8.37046, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 7, -7178.13, -3791.51, 8.37044, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 8, -7155.11, -3756.1, 8.3706, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 9, -7130.44, -3755.85, 9.371, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 10, -7101.19, -3760.75, 8.409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 11, -7101.46, -3751.12, 8.371, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 12, -7144.51, -3749.81, 8.383, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 13, -7144.3, -3741.95, 8.375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 14, -7117.47, -3741.74, 8.373, 500, 303, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (7583, 15, -7111.11, -3741.78, 8.60926, 0, 304, 0, 0, 0, 0, 0, 0, 0, 0, 3.9968, 0, 0);

-- Waypoints for Quixxil
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 1, -6197.86, -1082.17, -209.164, 1500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.43314, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 2, -6199.56, -1085.36, -211.208, 500, 305, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 3, -6198.63, -1095.16, -214.588, 500, 0, 2000007036, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 4, -6194.23, -1109.09, -218.586, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 5, -6184.15, -1130.37, -217.077, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 6, -6203.27, -1111.44, -219.372, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 7, -6213.76, -1080.86, -211.628, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 8, -6184.81, -1050.6, -191.913, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 9, -6173.85, -1054.14, -190.152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 10, -6179.2, -1041.91, -185.499, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10977, 11, -6197.86, -1082.17, -209.164, 0, 307, 0, 0, 0, 0, 0, 0, 0, 0, 4.43314, 0, 0);

-- Waypoints for Legacki
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 1, 6705.61, -4686.18, 721.974, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.436332, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 2, 6713.69, -4682.37, 721.616, 500, 0, 2000007031, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 3, 6731.52, -4675.63, 721.208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 4, 6736.81, -4672.96, 721.913, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 5, 6749.89, -4662.13, 725.001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 6, 6750.16, -4661.56, 724.987, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 7, 6732.86, -4641.78, 722.878, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 8, 6727.72, -4641.23, 721.686, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 9, 6715.98, -4643.64, 721.197, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 10, 6719.31, -4652.82, 721.231, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 11, 6715, -4685.52, 721.466, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 12, 6718.75, -4705.67, 721.91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 13, 6712.26, -4717.95, 721.508, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 14, 6701.64, -4714.28, 721.653, 0, 303, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 15, 6701.11, -4695.85, 722.361, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (10978, 16, 6705.61, -4686.18, 721.974, 0, 308, 0, 0, 0, 0, 0, 0, 0, 0, 0.436332, 0, 0);
