DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20191116204223');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20191116204223');
-- Add your query below.


-- Quest greetings
UPDATE `quest_greeting` SET `content_loc8` = "Приключения в ближних и дальних землях$BВстреча со странными и не странными людьми$BНо если у тебя есть, на который ты хочешь знать ответ$BСперва нужно решить простую задачу!" WHERE `entry` = 239;
UPDATE `quest_greeting` SET `content_loc8` = "Ага! Добрый день, добрый день, мастер $c! Пойдем, присядем и выпьем. У тебя предприимчивый взгляд, и я думаю, что ты не зря потратишь время на разговор со мной..." WHERE `entry` = 253;
UPDATE `quest_greeting` SET `content_loc8` = "Если ты просто прогуливаешься, $c, то лучше держаться дороги и делать это только днем. Если дела ждут тебя здесь в Темнолесье, то стоит заглянуть к Ночному Дозору. Наши навыки неоспоримы, но ряды наши малы." WHERE `entry` = 264;
UPDATE `quest_greeting` SET `content_loc8` = "Я знал, что ты придешь, $n. Звезды рассказали мне об этом." WHERE `entry` = 265;
UPDATE `quest_greeting` SET `content_loc8` = "Добро пожаловать в Темнолесье. Клерк Далтри к вашим услугам. Могу ли я чем-то помочь?" WHERE `entry` = 267;
UPDATE `quest_greeting` SET `content_loc8` = "Привет, привет! Добро пожаловать на мою кухню, $gсэр:миледи;! Здесь вы найдете самые лучшие деликатесы таверны \"Алый ворон\". Ах, какой прекрасный аромат!" WHERE `entry` = 272;
UPDATE `quest_greeting` SET `content_loc8` = "Держи дверь закрытой, $c. Никогда не знаешь, когда Темные всадники пройдут здесь снова." WHERE `entry` = 273;
UPDATE `quest_greeting` SET `content_loc8` = "Здравствуйте, $gсэр:леди;. Присаживайтесь и если вы голодны, угощайтесь. Не обращайте внимания на мою занятость, я вас внимательно слушаю..." WHERE `entry` = 278;
UPDATE `quest_greeting` SET `content_loc8` = "А?!? Ох, вы не похожи на одного из членов Братства Справедливости... или Ночного Дозора. Не пощадите ли бедную душу?" WHERE `entry` = 288;
UPDATE `quest_greeting` SET `content_loc8` = "А? Приветствую вас, молодой $c. Вы очень смелы, раз пришли сюда мимо всех этих существ!$B$BХорошо, раз вы здесь, может, поможете старому отшельнику..." WHERE `entry` = 289;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую тебя, искатель приключений. Мое зрение уже не так хорошо, как было раньше, но я могу за милю услышать шаги $c. В течение долго времени я стоял на страже Штормграда, но как мое зрение подвело меня, я был вынужден уйти в отставку." WHERE `entry` = 294;
UPDATE `quest_greeting` SET `content_loc8` = "Добро пожаловать в Башню Азоры, молодой $c. Я Теокрит.$B$BУ тебя есть ко мне какие-то вопросы? Или... у тебя есть вопросы к себе?" WHERE `entry` = 313;
UPDATE `quest_greeting` SET `content_loc8` = "У меня нет времени на разговоры, $n. Мне нужно разобраться с этим мостом до того как пойдет дождь. Я каждый проект заканчивал вовремя, и не собираюсь прокалываться сейчас." WHERE `entry` = 341;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую, $n! Добро пожаловать в мой скромный сад. В эти дни погода прекрасна. Будем надеяться, что она останется такой же до созревания урожая." WHERE `entry` = 342;
UPDATE `quest_greeting` SET `content_loc8` = "Красногорье погружено в хаос!" WHERE `entry` = 344;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую, $c. Если вы здесь по делам, тогда берите себе настойку и обсудим ваши дела." WHERE `entry` = 381;
UPDATE `quest_greeting` SET `content_loc8` = "У меня нет времени на болтовню. Но если ты $Gготов:готова; протянуть нам руку помощи в сражении против орков, тогда я найду тебе применение." WHERE `entry` = 382;
UPDATE `quest_greeting` SET `content_loc8` = "Не бойся, $r. Меня уже давно нет в этом мире, и я не желаю тебе зла. В свое время мне пришлось повидать слишком много смертей и моим единственным желанием сейчас является достижение мира. Возможно, ты сможешь помочь моему делу." WHERE `entry` = 392;
UPDATE `quest_greeting` SET `content_loc8` = "Эй $gприятель:мэм;, думаете, вы сможете мне что-то дать? Я и вправду в ужасном положении здесь..." WHERE `entry` = 415;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую тебя, $c. Сейчас настали плохие времена для нашего города, друг мой. Орки ведут свои атаки со стороны крепости Каменной Стражи, Темношкуры маячат у башни Илгалара, а гноллы Красногорья собираются с силами. Надеюсь, ты здесь не для отдыха..." WHERE `entry` = 464;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую, $c. Если ты $Gодин:одна; из приспешников полковника Курцена, тогда стой где стоишь! Но если ты здесь чтобы помочь нам, тогда я слушаю..." WHERE `entry` = 469;
UPDATE `quest_greeting` SET `content_loc8` = "Пришли темные времена, $c... Скоро мы все потеряем... Свет покинет всех." WHERE `entry` = 633;
UPDATE `quest_greeting` SET `content_loc8` = "Бандиты были всюду!$B$BЭто было ужасно. Пещера обвалилась на нас. Думаю, вся добывающая компания мертва, включая моего брата, Штейгера." WHERE `entry` = 656;
UPDATE `quest_greeting` SET `content_loc8` = "Семья Карвин сражается во имя Света. Моя служба Свету дает мне сил в сражении против нежити. Мастер Карвин поручил мне уничтожить мерзких воргенов в Сумеречном лесу. Может, ты мне поможешь?" WHERE `entry` = 663;
UPDATE `quest_greeting` SET `content_loc8` = "Еще один прекрасный день в джунглях! Сегодня будет отличная охота, я чувствую это. Как только Барнил завершит с чисткой моего оружия, я отправлюсь на охоту. Не так уж и плохо для ветерана войны, а?" WHERE `entry` = 715;
UPDATE `quest_greeting` SET `content_loc8` = "Смотри куда ступаешь, $gпарень:девушка;. Возможно, ты и не являешься частью нашей группы, но это не означает что я не подам тебе трость, если ты упадешь." WHERE `entry` = 733;
UPDATE `quest_greeting` SET `content_loc8` = "Какие дела привели тебя к ратуше Приозерья и уважаемому мировому судье Соломону?" WHERE `entry` = 900;
UPDATE `quest_greeting` SET `content_loc8` = "Защита моста Тандола была не простой задачей. Мы сконцентрировали свои здесь, сражаясь за это место, но Дун Модр пал." WHERE `entry` = 1071;
UPDATE `quest_greeting` SET `content_loc8` = "Знаешь, мне всегда хотелось стать геологом, но моя голова с рождения все очень хорошо запоминала и Гильдия решила повесить на меня ответственность за книги! Изучение, изучение, каждый день изучение..." WHERE `entry` = 1105;
UPDATE `quest_greeting` SET `content_loc8` = "Привет. Меня зовут Тупонос, мировой судья Тупонос, если быть точнее. Мне поручено следить за благополучием Телсамара." WHERE `entry` = 1139;
UPDATE `quest_greeting` SET `content_loc8` = "Если вы здесь ради еды, тогда добро пожаловать! Вы не найдете еду лучше во всем Штормграде... или Азероте!$B$BЕсли вы здесь по другим вопросам, тогда, пожалуйста, давайте быстрее. У меня готовится очень много блюд и мне нужно позаботиться о каждом из них." WHERE `entry` = 1141;
UPDATE `quest_greeting` SET `content_loc8` = "Если вы готовы выслушать дюжину рассказов, тогда присаживайтесь перед заклинением..." WHERE `entry` = 1239;
UPDATE `quest_greeting` SET `content_loc8` = "Трогги! Клянусь, сами боги разместили их здесь, чтобы досаждать мне!" WHERE `entry` = 1254;
UPDATE `quest_greeting` SET `content_loc8` = "Добро пожаловать в нашу таверну! Я управляю этим местом с тех пор, как мой брат Мрачнобух исчез в пьяном кураже несколько урожаев назад." WHERE `entry` = 1267;
UPDATE `quest_greeting` SET `content_loc8` = "Мы уже долго возимся с этими руинами, но, надеюсь, это не продлится долго. Тем временем, можно было бы использовать кого-то вроде тебя. Не желаешь помочь Лиге исследователей?" WHERE `entry` = 1344;
UPDATE `quest_greeting` SET `content_loc8` = "У меня сейчас очень важное задание. Если у вас есть что-то очень срочное для меня, о чем я очень сомневаюсь, тогда, давайте поговорим." WHERE `entry` = 1356;
UPDATE `quest_greeting` SET `content_loc8` = "Вы нигде не найдете знаний больше, чем в Королевской библиотеке!" WHERE `entry` = 1440;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую. Я Барос Алекстон, городской архитектор Штормграда." WHERE `entry` = 1646;
UPDATE `quest_greeting` SET `content_loc8` = "Здесь ты $Gбесполезен:бесполезна;... ! Если ты действительно хочешь сделать что-то полезное, тогда слушай внимательно!" WHERE `entry` = 1719;
UPDATE `quest_greeting` SET `content_loc8` = "Я Болвар Фордрагон, верховный лорд Штормграда." WHERE `entry` = 1748;
UPDATE `quest_greeting` SET `content_loc8` = "Большую часть нашей жизни мы провели, сражаясь, а воспоминания о мирных временах уже стерлись из памяти." WHERE `entry` = 1776;
UPDATE `quest_greeting` SET `content_loc8` = "Мы с братом выполняем разведывательную миссию, но застряли в этом доме. Ловчим смерти нужна ваша помощь!" WHERE `entry` = 1950;
UPDATE `quest_greeting` SET `content_loc8` = "Меня обучали служить обществу. Быть представителем народа. Мои навыки это не умение обращаться с оружием или в ремесле, а иметь подходящие слова и умение убеждать." WHERE `entry` = 1977;
UPDATE `quest_greeting` SET `content_loc8` = "Создание Тельдрассила было огромным достижением, но теперь, чтобы восстановить равновесия, мир должен измениться." WHERE `entry` = 2080;
UPDATE `quest_greeting` SET `content_loc8` = "Осадные машины – гордость каждого пилота!" WHERE `entry` = 2092;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую вас, $c. Мы сейчас находимся в затруднительном положении, у нас очень мало шкур." WHERE `entry` = 2094;
UPDATE `quest_greeting` SET `content_loc8` = "Мы так близки к созданию Новой Чумы, которую с таким нетерпением ждет наша Темная Госпожа." WHERE `entry` = 2216;
UPDATE `quest_greeting` SET `content_loc8` = "Надеюсь, $c, вы здесь для того чтобы поработать. Нам необходимо многое сделать, а Орда, Синдикат и Огры не помогут нам." WHERE `entry` = 2263;
UPDATE `quest_greeting` SET `content_loc8` = "Когда мне впервые предложили звание судьи Южнобережья, я был очень рад, что получил такой титул в самом начале своей карьеры.$B$BНо теперь, когда я здесь, я задаюсь вопросом, что было бы лучше, если бы я остался перебирать бумаги в Штормграде." WHERE `entry` = 2276;
UPDATE `quest_greeting` SET `content_loc8` = "А? Какие дела привели тебя к Нимбойе?" WHERE `entry` = 2497;
UPDATE `quest_greeting` SET `content_loc8` = "Йоу! Хочешь сыграть?" WHERE `entry` = 2501;
UPDATE `quest_greeting` SET `content_loc8` = "Опорный Пункт одно из немногих мест оставшееся от былого величия Стромграда, здесь в Нагорье Арати. Но мы теряем эти земли...$B$BЕсли у вас есть вести для меня, то я надеюсь что они хорошие." WHERE `entry` = 2700;
UPDATE `quest_greeting` SET `content_loc8` = "Благодаря Вождю, даже здесь, в руинах нашей некогда тюрьмы, остается надежда, что однажды Орда вновь возродится." WHERE `entry` = 2706;
UPDATE `quest_greeting` SET `content_loc8` = "На этой деревянной доске размещены различные объявления о розыске." WHERE `entry` = 2713;
UPDATE `quest_greeting` SET `content_loc8` = "Назад! У меня в руках взрывчатка наполненная порохом, и я не побоюсь ее использовать! Я убью нас всех!$B$BОх, не обращай внимания. Я думал, что это кто-то другой..." WHERE `entry` = 2785;
UPDATE `quest_greeting` SET `content_loc8` = "Добро пожаловать в лавку Костохвата, $c. Вы можете смотреть, но ничего не трогайте.$B$BНекоторые из знаний, не предназначены для... непосвященных." WHERE `entry` = 2786;
UPDATE `quest_greeting` SET `content_loc8` = "Должно быть, тебе сложно бродить по этим Бесплодным землям, $c. Сложно, как и мне.$B$BИли может, ты здесь лишь потому что $gтакой же сумасшедший:такая же сумасшедшая; как и я." WHERE `entry` = 2817;
UPDATE `quest_greeting` SET `content_loc8` = "Это было довольно неплохое отступление я вам скажу, $c. Мы хватали все, что можно было унести, и от этого наши запасы не так велики." WHERE `entry` = 2860;
UPDATE `quest_greeting` SET `content_loc8` = "Они пришли ночью, как раз после того, как мы употребили несколько крепких напитков. В противном случае, мы бы схватили их.$B$BТеперь все мертвы... кроме нескольких из нас." WHERE `entry` = 2910;
UPDATE `quest_greeting` SET `content_loc8` = "Привет, $n.$B$BЛотвитль не самый лучший босс, который у меня когда-то был. Он очень погружен в свою работу, настолько, что иногда его прислужники остаются голодными или без оплаты.$B$B$B$B*Люсьен хмуро смотрит на Лотвитля.*" WHERE `entry` = 2920;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую, $c. В свои годы мне доводилось видеть множество нетерпеливых тауренов, которые хотят доказать свою ценность племени. Но не следует забывать, что стремление не заменит мудрость и опыт." WHERE `entry` = 2981;
UPDATE `quest_greeting` SET `content_loc8` = "Эта земля благосклонна к нашему народу, $c. Мы должны быть благодарны за нашу удачу." WHERE `entry` = 2993;
UPDATE `quest_greeting` SET `content_loc8` = "Лезвие топора оставит брызги крови врага на твоем лице. Это то, чего жаждет каждый воин, $n. Я очищу Степи, своим мечем, во имя Орды." WHERE `entry` = 3337;
UPDATE `quest_greeting` SET `content_loc8` = "Это было бы лучше..." WHERE `entry` = 3339;
UPDATE `quest_greeting` SET `content_loc8` = "В Степях находятся различные материалы, которым мы – аптекари Лордерона можем найти применение." WHERE `entry` = 3390;
UPDATE `quest_greeting` SET `content_loc8` = "Чтобы охотится на зверя, нужно знать этого зверя. Нужно изучать и уважать его пути.$B$BИначе это не охота, а просто убийство." WHERE `entry` = 3441;
UPDATE `quest_greeting` SET `content_loc8` = "Я Арания Проблеск Солнца, моя задача охранять Поляну Оракула." WHERE `entry` = 3519;
UPDATE `quest_greeting` SET `content_loc8` = "Приятно встретить вас, $n. Хорошо, что такой $c как вы, принимает активное участие в защите рощ." WHERE `entry` = 3567;
UPDATE `quest_greeting` SET `content_loc8` = "Доброго дня! Возможно, вы бы смогли мне помощь с некоторыми вещами, о которых необходимо позаботиться." WHERE `entry` = 3663;
UPDATE `quest_greeting` SET `content_loc8` = "Хм... я могу подключить этот провод сюда, и тогда механизм придет в действие, но тогда для гиро потребуется альтернативный источник питания... Возможно, я могу... О, привет! Не хочешь помочь мне с новым изобретением?" WHERE `entry` = 3666;
UPDATE `quest_greeting` SET `content_loc8` = "Ясеневый лес – пышный, наполненный жизнью лес. Очень приятно ходить по тайным тропам в поиске трав. Но этот лес не лишен опасностей." WHERE `entry` = 3847;
UPDATE `quest_greeting` SET `content_loc8` = "Природный баланс очень хрупок. Но достаточно ли вы храбры, чтобы все исправить?" WHERE `entry` = 3848;
UPDATE `quest_greeting` SET `content_loc8` = "Духи обеспокоены!" WHERE `entry` = 3995;
UPDATE `quest_greeting` SET `content_loc8` = "Тебе стоит прислушаться, юный $c. Прислушайся к шепотам во тьме, они дадут совет в эти темные времена." WHERE `entry` = 4046;
UPDATE `quest_greeting` SET `content_loc8` = "Дух Когтистых гор плачет... Он плачет от своих горных вершин до рек, срезанных и мертвых деревьев." WHERE `entry` = 4049;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую, $gдруг:подруга;. Что я могу сделать для вас?" WHERE `entry` = 4078;
UPDATE `quest_greeting` SET `content_loc8` = "Подойди поближе. Есть важные вопросы, которые нам следует обсудить.$B$BНо и есть то, чего не следует тебе слышать..." WHERE `entry` = 4452;
UPDATE `quest_greeting` SET `content_loc8` = "Нет, Длинноушка не мое настоящее имя. И я не сообщу тебе, что это означает, даже не спрашивай." WHERE `entry` = 4456;
UPDATE `quest_greeting` SET `content_loc8` = "Дни длятся очень долго, а конфликтам на этих землях нет конца. Возьми свое оружие, $c. Война может придти в любое время, и если я не ошибаюсь, ты выглядишь как $gодин:одна; из тех, кто упивается ею." WHERE `entry` = 4485;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую вас, $c." WHERE `entry` = 4498;
UPDATE `quest_greeting` SET `content_loc8` = "Властитель Мок'Морокк здесь босс, и ты будешь делать то, что я скажу." WHERE `entry` = 4500;
UPDATE `quest_greeting` SET `content_loc8` = "Некоторые говорят, что болота это не хорошо... ничего хорошего, говорят они." WHERE `entry` = 4792;
UPDATE `quest_greeting` SET `content_loc8` = "Альянс имеет много ставок здесь в Пустошах, и наша позиция здесь неустойчива.$B$BПоможете ли вы нам?" WHERE `entry` = 5396;
UPDATE `quest_greeting` SET `content_loc8` = "Кланы кентавров управляют участками Пустошей. Если бы они объединились, то они бы стали ужасной силой. Очень хорошо, что кланы вместо объединения выбрали путь сражения друг с другом." WHERE `entry` = 5412;
UPDATE `quest_greeting` SET `content_loc8` = "О чем ты хочешь спросить меня?" WHERE `entry` = 5598;
UPDATE `quest_greeting` SET `content_loc8` = "У меня много дел здесь в Пустошах, $n. Ройттен хочет, чтобы мы забрали некоторые реагенты для одного из наших клиентов, а также доставили несколько утраченных предметов.$B$BПохоже, что ты здесь чтобы помочь нам, так почему бы нам не начать?" WHERE `entry` = 5638;
UPDATE `quest_greeting` SET `content_loc8` = "Главная угроза, с которой Тралл хочет расправиться, это Пылающий Клинок – члены Орды, которые дали клятву своей верности демонам. Они стремятся к тому, чтобы улучшать свои навыки темной магии, и их мало заботят видения Тралла о будущем Орды здесь в Калимдоре." WHERE `entry` = 5641;
UPDATE `quest_greeting` SET `content_loc8` = "Нашей единственной надеждой является появление чего-то хорошего в ужасной ситуации." WHERE `entry` = 5767;
UPDATE `quest_greeting` SET `content_loc8` = "Некоторые не могут выдержать тот жар, исходящий от Великой Кузни, но я считаю, что с этим здесь все в порядке. Это лучшее место для того, чтобы в серьез заняться кузнечным делом." WHERE `entry` = 6031;
UPDATE `quest_greeting` SET `content_loc8` = "Многие испытания ждут паладина Света, $n. Будьте уверены, в будущем, наши пути еще много раз пересекутся, если же вы все также останетесь верны своей страсти и не отбросите те качества, которые мы возвышаем." WHERE `entry` = 6179;
UPDATE `quest_greeting` SET `content_loc8` = "Там где обитают Трогги и лепрогномы, наш дом – Гномреган.$B$BНаши семьи потеряны, наш дом теперь теперь другой.$B$BОх, как хочется вернуться в те беззаботные дни жизни в Гномрегане, но этих дней больше нет. Мы должны укрепить нашу позицию! Мы должны вернуть Гномреган!" WHERE `entry` = 6569;
UPDATE `quest_greeting` SET `content_loc8` = "За Гномреган!" WHERE `entry` = 6579;
UPDATE `quest_greeting` SET `content_loc8` = "Меня зовут, Дран Дрофферс, а это мой глупый сын, Мальтон. Если вам нужна помощь или вы хотите продать некоторые из своих вещей, тогда мы именно те, кто вам нужен!" WHERE `entry` = 6986;
UPDATE `quest_greeting` SET `content_loc8` = "$gДорогой друг:Дорогая подруга;, вы прибыли как раз вовремя, чтобы оказать помощь экспедиционному корпусу Каргата." WHERE `entry` = 9078;
UPDATE `quest_greeting` SET `content_loc8` = "Я никогда не промахиваюсь..." WHERE `entry` = 9081;
UPDATE `quest_greeting` SET `content_loc8` = "Будь начеку, солдат!$B$BТИХО!" WHERE `entry` = 9177;
UPDATE `quest_greeting` SET `content_loc8` = "Поиск сокровища – единственная значимая цель для гоблина.$B$BНу, может, сокровища... и большая, громкая смерть!" WHERE `entry` = 9536;
UPDATE `quest_greeting` SET `content_loc8` = "Приветствую вас, $r." WHERE `entry` = 9562;
UPDATE `quest_greeting` SET `content_loc8` = "Добро пожаловать в экзотический питомник Киблера! Чем вы можете мне сегодня помочь?" WHERE `entry` = 10260;
UPDATE `quest_greeting` SET `content_loc8` = "Мы не можем разобраться со всеми угрозами, находящимися в этой местности. И мы бы не отказались воспользоваться рукой помощи, $n." WHERE `entry` = 10537;
UPDATE `quest_greeting` SET `content_loc8` = "Я больше никогда не почувствую тепла..." WHERE `entry` = 10926;

-- Trainer greetings
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 198;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 328;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 331;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 375;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 376;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 377;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 459;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 460;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 461;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 514;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 812;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 837;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 895;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 906;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 908;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 911;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 912;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 913;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 914;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 915;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 916;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 917;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 918;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 925;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 926;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 927;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 928;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 944;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 985;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 986;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 987;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 988;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 1103;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 1215;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 1218;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 1226;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 1228;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 1229;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 1231;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 1232;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 1234;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 1241;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 1292;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 1300;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 1317;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 1346;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 1355;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 1382;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 1385;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 1386;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 1404;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 1411;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 1430;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 1458;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 1470;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 1473;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 1632;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 1651;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 1676;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 1680;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 1681;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 1683;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 1699;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 1700;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 1701;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 1702;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 1703;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 1901;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 2114;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 2119;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 2122;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 2123;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 2124;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 2126;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 2127;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 2128;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 2129;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 2130;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 2131;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 2132;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 2326;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 2327;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 2329;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 2367;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 2390;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 2391;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 2399;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Добро пожаловать!" WHERE `entry` = 2485;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Добро пожаловать!" WHERE `entry` = 2489;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Добро пожаловать!" WHERE `entry` = 2492;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 2627;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 2798;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 2818;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 2834;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 2836;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 2837;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 2855;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 2856;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 2998;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 3001;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 3004;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3007;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 3009;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 3011;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 3013;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 3026;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 3028;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3030;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3031;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3032;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3033;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3034;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3036;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3038;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3039;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3040;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3041;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3042;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3043;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3044;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3045;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3046;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 3047;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 3048;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 3049;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3059;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3060;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3061;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3062;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3063;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3064;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3065;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3066;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 3067;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3069;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 3087;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 3136;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 3137;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3153;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3154;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3155;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 3156;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3157;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3169;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3170;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3171;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 3172;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3173;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 3174;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 3175;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 3179;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 3181;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 3184;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 3185;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 3290;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 3324;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 3325;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 3326;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3327;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3328;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 3332;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3344;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 3345;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 3347;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3352;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3353;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3354;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 3355;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 3357;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 3363;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3365;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 3373;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 3399;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3401;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 3403;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 3404;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3406;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3407;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3408;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 3478;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 3484;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 3494;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 3523;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3549;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 3555;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 3557;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3593;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3594;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3595;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3596;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3597;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 3598;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 3599;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3600;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3601;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 3602;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 3603;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 3604;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3605;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 3606;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 3607;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 3690;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3703;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 3704;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3706;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 3707;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 3963;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 3964;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 3965;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 3967;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 4087;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 4089;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 4090;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 4091;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 4092;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 4138;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 4146;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 4156;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 4159;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 4160;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 4163;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Добро пожаловать!" WHERE `entry` = 4165;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 4193;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 4204;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 4205;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 4210;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 4211;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 4212;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 4213;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 4214;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 4215;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 4217;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 4218;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 4219;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 4254;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 4258;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 4552;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 4563;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 4564;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 4565;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 4566;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 4567;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 4568;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 4573;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 4576;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 4578;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 4582;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 4583;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 4584;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 4588;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 4591;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 4593;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 4594;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 4595;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 4596;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 4598;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 4606;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 4607;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 4608;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 4611;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 4614;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 4616;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 4732;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 4752;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 4753;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 4772;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 4773;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 4898;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 4900;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 5032;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 5037;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 5038;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 5040;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 5041;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 5113;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 5114;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5115;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5116;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5117;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 5127;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 5137;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 5141;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 5142;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 5143;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5144;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5145;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5146;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 5147;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 5148;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 5149;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 5150;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 5153;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 5157;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 5159;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 5161;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 5164;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 5165;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 5166;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 5167;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 5171;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 5172;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 5173;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 5174;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 5177;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 5392;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 5479;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 5480;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 5482;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 5484;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 5489;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 5491;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 5492;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 5493;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 5495;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 5496;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5497;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5498;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 5499;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5501;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 5502;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 5504;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 5505;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 5506;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 5511;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 5513;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5515;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5516;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 5517;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 5518;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 5564;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 5566;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 5612;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 5690;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 5695;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 5759;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 5784;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5880;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5882;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5883;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5884;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 5885;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 5938;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 5939;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 5941;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 5943;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Добро пожаловать!" WHERE `entry` = 5957;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Добро пожаловать!" WHERE `entry` = 5958;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 5994;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 6014;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 6018;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Позвольте мне показать вам, как обработать эти раны..." WHERE `entry` = 6094;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gчернокнижник:чернокнижница;! Готовы к обучению?" WHERE `entry` = 6251;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 6286;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6287;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6288;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6289;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6290;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6291;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6292;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6295;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 6297;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 6299;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6306;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 6387;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 6707;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 7087;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 7088;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 7089;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 7230;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 7231;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 7232;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 7311;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, маг! Готовы к обучению?" WHERE `entry` = 7312;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 7315;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 7406;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 7866;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 7867;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 7868;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 7869;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 7870;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 7871;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 7944;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 7946;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "С алхимией вы можете превращать найденные траву в различные виды зелий, в том числе и исцелений." WHERE `entry` = 7948;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 7949;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 7953;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Здравствуйте! Могу ли я вас чему-то обучить?" WHERE `entry` = 7954;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 8126;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Вы и жизни не видали, если не копались в земле." WHERE `entry` = 8128;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, паладин! Готовы к обучению?" WHERE `entry` = 8140;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, воин! Готовы к обучению?" WHERE `entry` = 8141;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 8142;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 8144;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 8146;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 8153;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Могу ли я обучить вас как превращать мясо, добытое с животных во вкусную еду?" WHERE `entry` = 8306;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 8308;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 8736;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 8738;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 9465;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 9584;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gохотник:охотница;! Готовы к обучению?" WHERE `entry` = 10930;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 10993;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 11017;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 11025;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 11031;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Инженерия это очень просто, главное понять принцип работы." WHERE `entry` = 11037;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 11048;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 11050;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 11051;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 11052;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 11072;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 11073;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Наложение чар – искусство улучшения существующих предметов с помощью магии." WHERE `entry` = 11074;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 11097;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать шкуру, добытую с животных в доспех?" WHERE `entry` = 11098;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 11146;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 11177;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Желаете обучиться тому, как превращать руду в оружие и металлическую броню?" WHERE `entry` = 11178;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 11397;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 11401;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gжрец:жрица;! Готовы к обучению?" WHERE `entry` = 11406;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую! Могу ли я обучить вас как превращать ткань в тканевую броню?" WHERE `entry` = 11557;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Поиск трав требует как знаний, так и инстинкта." WHERE `entry` = 12025;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Чтобы снять шкуру с убитого зверя, необходима твердость рук." WHERE `entry` = 12030;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 12032;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, друид! Готовы к обучению?" WHERE `entry` = 12042;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 12961;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gразбойник:разбойница;! Готовы к обучению?" WHERE `entry` = 13283;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Приветствую вас, $gшаман:шаманка;! Готовы к обучению?" WHERE `entry` = 13417;
UPDATE `npc_trainer_greeting` SET `content_loc8` = "Я могу обучить вас как использовать удочку для ловли рыбы." WHERE `entry` = 14740;


-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
