INSERT INTO `migrations` VALUES ('20170722110502'); 

-- Script for quest Forsaken Aid (1064)
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000000033, '%s summons a messenger...', '%s|1이;가; 전령을 소환합니다...', '%s convoque un messager…', '%s beschwört einen Boten...', '%s召唤出一个信使……', '%s召來了一個信差...', '%s llama a un mensajero...', '%s llama a un mensajero...', '%s призывает гонца...');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000000034, 'Go, my servant.  Send word of Stonetalon to Apothecary Zamah.', '가라, 나의 충직한 아이야. 연금술사 자마에게 돌발톱 산맥의 전언을 전하라.', 'Va, mon serviteur. Apporte les nouvelles des Serres-Rocheuses à l’apothicaire Zamah.', 'Geht, mein Diener. Bringt Kunde vom Steinkrallengebirge zu Apothekerin Zamah.', '去吧，我的仆人。把石爪山的消息带给药剂师扎玛。', '去吧，我的僕人。把石爪山的消息帶給藥劑師札瑪。', 'Ve, mi sirviente. Envía un mensaje del Espolón a la boticaria Zamah.', 'Ve, mi sirviente. Envía un mensaje del Espolón a la boticaria Zamah.', 'Ступай, $gмой подданный:моя подданная;. Передай послание Каменного Когтя аптекарю Зама.');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000000035, '%s gives message to Apothecary Zamah.', '%s|1이;가; 연금술사 자마에게 전갈을 전합니다.', '%s remet un message à l’apothicaire Zamah.', '%s übergibt Apothekerin Zamah eine Nachricht.', '%s把信交给了药剂师扎玛。', '%s把信交給了藥劑師札瑪。', '%s lleva el mensaje a la boticaria Zamah.', '%s lleva el mensaje a la boticaria Zamah.', '%s передает сообщение аптекарю Заме.');
INSERT INTO `db_script_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (2000000036, '%s smiles.', '%s|1이;가; 미소를 짓습니다.', '%s sourit.', '%s lächelt.', '%s微微一笑。', '%s微笑。', '%s sonríe.', '%s sonríe.', '%s улыбается.');

DELETE FROM `quest_start_scripts` WHERE `id`=1064;
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 2, 0, 2, 0, 0, 0, 0, 2000000033, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Magatha Grimtotem Say Emote Text 1');
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 2, 15, 6657, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Cast Summon Serpent Messenger');
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 3, 10, 4068, 130000, 0, 0, 0, 0, 0, 0, 0, -1067.22, -213.737, 160.473, 5.25037, 'Forsaken Aid - Summon Serpent Messenger');
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 4, 25, 1, 4068, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Serpent Messenger Set Run');
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 4, 20, 2, 4068, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Serpent Messenger Start Waypoint Movement');
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 5, 1, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Magatha Grimtotem Emote Point');
INSERT INTO `quest_start_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (1064, 5, 0, 0, 0, 0, 0, 0, 2000000034, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Magatha Grimtotem Say Text 2');

DELETE FROM `creature_movement_scripts` WHERE `id`=406801;
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (406801, 2, 0, 2, 0, 0, 0, 0, 2000000035, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Serpent Messenger Say Emote Text');
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES (406801, 5, 0, 2, 3419, 10, 0, 0, 2000000036, 0, 0, 0, 0, 0, 0, 0, 'Forsaken Aid - Apothecary Zamah Say Emote Text');

UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry`=4068;

UPDATE `quest_template` SET `StartScript`=1064 WHERE `entry`=1064;