DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20171206145835');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20171206145835');
-- Add your query below.


ALTER TABLE `gossip_menu_option`
	ADD COLUMN `OptionBroadcastTextID` MEDIUMINT(6) UNSIGNED NOT NULL DEFAULT '0' AFTER `option_text`,
	ADD COLUMN `BoxBroadcastTextID` MEDIUMINT(6) UNSIGNED NOT NULL DEFAULT '0' AFTER `box_text`;
	
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3370 WHERE `option_text`='I want to browse your goods.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3409 WHERE `option_text`='I need a ride.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3266 WHERE `option_text`='Train me.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2547 WHERE `option_text`='Return me to life.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2822 WHERE `option_text`='Make this inn your home.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3398 WHERE `option_text`='I would like to check my deposit box.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3413 WHERE `option_text`='How do I form a guild?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3415 WHERE `option_text`='I want to create a guild crest.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10553 WHERE `option_text`='I wish to join the battle!';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=30181 WHERE `option_text`='I\'d like to stable my pet here.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3370 WHERE `option_text`='GOSSIP_OPTION_ARMORER';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8271 WHERE `option_text`='I wish to unlearn my talents.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2466 WHERE `menu_id`=21 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4384 WHERE `menu_id`=21 && `id`=1;
UPDATE `broadcast_text` SET `MaleText`='Can you tell me about this shard?', `FemaleText`='Can you tell me about this shard?' WHERE `ID`=4384;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2522 WHERE `option_text`='I am interested in mage training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2846 WHERE `menu_id`=321 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10693 WHERE `option_text`='Trick or Treat!';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2822 WHERE `option_text`='Make this inn my home.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8097 WHERE `option_text`='Let me browse your goods.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9882 WHERE `option_text`='Tell me about dungeons I could explore.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4308 WHERE `option_text`='What can I do at an inn?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2862 WHERE `menu_id`=381 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3446 WHERE `option_text`='Druid';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3447 WHERE `option_text`='Hunter';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3448 WHERE `option_text`='Mage';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5102 WHERE `option_text`='Paladin';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3449 WHERE `option_text`='Priest';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4885 WHERE `option_text`='Rogue';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4886 WHERE `option_text`='Warlock';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2910 WHERE `option_text`='Warrior';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8221 WHERE `option_text`='I would like to train.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2931 WHERE `menu_id`=411 && `id`=0;
UPDATE `broadcast_text` SET `MaleText`='<Take the letter>', `FemaleText`='<Take the letter>' WHERE `ID`=8548;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8548 WHERE `option_text`='<Take the letter>';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3460 WHERE `option_text`='Alchemy';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3461 WHERE `option_text`='Blacksmithing';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3462 WHERE `option_text`='Cooking';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3463 WHERE `option_text`='Enchanting';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4976 WHERE `option_text`='Engineering';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3464 WHERE `option_text`='First Aid';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3465 WHERE `option_text`='Fishing';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3466 WHERE `option_text`='Herbalism';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3467 WHERE `option_text`='Leatherworking';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3468 WHERE `option_text`='Mining';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3471 WHERE `option_text`='Skinning';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3469 WHERE `option_text`='Tailoring';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5316 WHERE `option_text`='Auction House';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2749 WHERE `option_text`='Bank of Stormwind';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6328 WHERE `option_text`='Deeprun Tram';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5090 WHERE `option_text`='The Inn';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5081 WHERE `option_text`='Gryphon Master';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2870 WHERE `option_text`='Guild Master';
UPDATE `broadcast_text` SET `MaleText`='Guild Master', `FemaleText`='Guild Master' WHERE `ID`=2870;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8511 WHERE `option_text`='Stable Master';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7241 WHERE `option_text`='Weapons Trainer';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9749 WHERE `option_text`='Officers\' Lounge';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10362 WHERE `option_text`='Battlemaster';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3429 WHERE `option_text`='Class Trainer';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3430 WHERE `option_text`='Profession Trainer';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2978 WHERE `option_text`='Hello! I am a Rogue in need of training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3147 WHERE `option_text`='I require warrior training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4888 WHERE `option_text`='The bank';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6632 WHERE `option_text`='The wind rider master';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3428 WHERE `option_text`='The guild master';
UPDATE `broadcast_text` SET `MaleText`='The guild master', `FemaleText`='The guild master' WHERE `ID`=3428;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5514 WHERE `option_text`='The mailbox';
UPDATE `broadcast_text` SET `MaleText`='The mailbox', `FemaleText`='The mailbox' WHERE `ID`=5514;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5515 WHERE `option_text`='The auction house';
UPDATE `broadcast_text` SET `MaleText`='The auction house', `FemaleText`='The auction house' WHERE `ID`=5515;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7253 WHERE `option_text`='The weapon master';
UPDATE `broadcast_text` SET `MaleText`='The weapon master', `FemaleText`='The weapon master' WHERE `ID`=7253;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8508 WHERE `option_text`='The stable master';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10359 WHERE `option_text`='The battlemaster';
UPDATE `broadcast_text` SET `MaleText`='The battlemaster', `FemaleText`='The battlemaster' WHERE `ID`=10359;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5338 WHERE `option_text`='A class trainer';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6635 WHERE `option_text`='A profession trainer';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3450 WHERE `option_text`='Shaman';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3662 WHERE `menu_id`=922 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6878 WHERE `menu_id`=3421 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4001 WHERE `option_text`='Acquire Higher Level Access Card';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4419 WHERE `menu_id`=1141 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4227 WHERE `menu_id`=1161 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4510 WHERE `option_text`='I am here for training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4851 WHERE `menu_id`=1403 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4519 WHERE `menu_id`=1422 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4573 WHERE `menu_id`=1482 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4634, `option_text`='I lost my transponder and need another one, Scooty.' WHERE `menu_id`=1628 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4713 WHERE `menu_id`=1781 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4793 WHERE `menu_id`=1882 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9756 WHERE `menu_id`=1951 && `id`=9;
UPDATE `broadcast_text` SET `MaleText`='The officers\' lounge', `FemaleText`='The officers\' lounge' WHERE `ID`=9756;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=22086 WHERE `option_text`='Where is the zeppelin now?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5040, `option_text`='Why don\'t you and Rocknot go find somewhere private...' WHERE `menu_id`=2076 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5078 WHERE `menu_id`=2121 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4895 WHERE `option_text`='Mailbox';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5186 WHERE `menu_id`=2184 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5188 WHERE `menu_id`=2184 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5190 WHERE `menu_id`=2184 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5299 WHERE `option_text`='I would like to train further in the ways of the Light.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5330 WHERE `menu_id`=2352 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5530 WHERE `menu_id`=2562 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5529 WHERE `menu_id`=2562 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6790 WHERE `menu_id`=2849 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5518 WHERE `menu_id`=2849 && `id`=6;
UPDATE `broadcast_text` SET `MaleText`='The zeppelin master', `FemaleText`='The zeppelin master' WHERE `ID`=5518;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2583 WHERE `option_text`='I would like to buy from you.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6659 WHERE `menu_id`=3301 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6661 WHERE `menu_id`=3303 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6657 WHERE `menu_id`=3304 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6655 WHERE `menu_id`=3305 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6653 WHERE `menu_id`=3306 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6651 WHERE `menu_id`=3307 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6649 WHERE `menu_id`=3308 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6647 WHERE `menu_id`=3309 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6645 WHERE `menu_id`=3310 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6799, `option_text`='Eva, I have lost the Spectral Essence. I need another.' WHERE `menu_id`=3310 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3427 WHERE `menu_id`=3331 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5909 WHERE `menu_id`=3356 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3426 WHERE `option_text`='Bank';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5513 WHERE `menu_id`=3506 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=3471 WHERE `menu_id`=3558 && `id`=11;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7069 WHERE `menu_id`=3580 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7072 WHERE `menu_id`=3580 && `id`=2;
UPDATE `broadcast_text` SET `MaleText`='The Guild Master', `FemaleText`='The Guild Master' WHERE `ID`=7072;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7139 WHERE `menu_id`=3624 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7157 WHERE `option_text`='I seek more training in the priestly ways.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7198 WHERE `menu_id`=3651 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10458 WHERE `menu_id`=3651 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10462 WHERE `menu_id`=3651 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7266 WHERE `menu_id`=3701 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7267 WHERE `menu_id`=3702 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7268 WHERE `menu_id`=3703 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7269 WHERE `menu_id`=3704 && `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7452 WHERE `option_text`='I seek training as a druid.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7517 WHERE `menu_id`=4009 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7519 WHERE `menu_id`=4010 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7521 WHERE `menu_id`=4011 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7523 WHERE `menu_id`=4012 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7549 WHERE `menu_id`=4017 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7556 WHERE `menu_id`=4023 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7615 WHERE `option_text`='Continue reading...';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7640 WHERE `menu_id`=4091 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2603 WHERE `option_text`='I would like training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7643 WHERE `option_text`='I seek training in the ways of the Hunter.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8262 WHERE `menu_id`=4461 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8272 WHERE `menu_id`=4463 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7491 WHERE `option_text`='Can you train me how to use rogue skills?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7658 WHERE `option_text`='Teach me the ways of the spirits.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7490 WHERE `option_text`='I\'m lookin\' for rogue trainin\'.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7478 WHERE `option_text`='I seek training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8295 WHERE `menu_id`=4606 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7658 WHERE `option_text`='Teach me the ways of the spirits.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=2544 WHERE `option_text`='I am interested in warlock training.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8298 WHERE `menu_id`=4669 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8292 WHERE `menu_id`=4670 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8404 WHERE `menu_id`=4671 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=7149 WHERE `option_text`='I\'d like to train.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8345 WHERE `menu_id`=4746 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=29625 WHERE `menu_id`=4783 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10621 WHERE `option_text`='I wish to untrain my pet.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8408 WHERE `menu_id`=4784 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8442 WHERE `option_text`='Please teach me.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8666 WHERE `menu_id`=5065 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12363 WHERE `menu_id`=5065 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8811 WHERE `option_text`='I\'d like some weapon training';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8812 WHERE `option_text`='What can other weapon masters teach?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20582 WHERE `option_text`='Crossbow';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20585 WHERE `option_text`='Gun';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20586 WHERE `option_text`='Mace';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20587 WHERE `option_text`='Polearm';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20588 WHERE `option_text`='Staff';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20589 WHERE `option_text`='Sword';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20583 WHERE `option_text`='Dagger';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20584 WHERE `option_text`='Fist Weapon';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20580 WHERE `option_text`='Axe';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20581 WHERE `option_text`='Bow';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=20590 WHERE `option_text`='Thrown';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8928 WHERE `menu_id`=5349 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8957 WHERE `menu_id`=5349 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8932 WHERE `menu_id`=5349 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8938 WHERE `menu_id`=5349 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8959 WHERE `menu_id`=5351 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8934 WHERE `menu_id`=5352 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8936 WHERE `menu_id`=5353 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8940 WHERE `menu_id`=5355 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8961 WHERE `menu_id`=5356 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8971 WHERE `menu_id`=5382 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8972 WHERE `menu_id`=5382 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8973 WHERE `menu_id`=5382 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9485 WHERE `menu_id`=5749 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9876 WHERE `menu_id`=6029 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9951 WHERE `menu_id`=6029 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9878 WHERE `menu_id`=6029 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9885 WHERE `menu_id`=6029 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9909 WHERE `menu_id`=6029 && `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9953 WHERE `menu_id`=6029 && `id`=5;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9915 WHERE `menu_id`=6029 && `id`=6;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9908 WHERE `menu_id`=6029 && `id`=7;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9918 WHERE `menu_id`=6029 && `id`=8;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9921 WHERE `menu_id`=6029 && `id`=9;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9931 WHERE `menu_id`=6029 && `id`=10;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9924 WHERE `menu_id`=6029 && `id`=11;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9928 WHERE `menu_id`=6029 && `id`=12;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9937 WHERE `menu_id`=6029 && `id`=13;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9934 WHERE `menu_id`=6029 && `id`=14;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9940 WHERE `menu_id`=6029 && `id`=15;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9942 WHERE `menu_id`=6029 && `id`=16;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9948 WHERE `menu_id`=6029 && `id`=17;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9945 WHERE `menu_id`=6029 && `id`=18;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9873 WHERE `option_text`='Join a group going to this dungeon.    <This choice will place you in a meetingstone queue>    ';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9898 WHERE `option_text`='Can you tell me more about this place?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10064 WHERE `menu_id`=6202 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10067 WHERE `menu_id`=6207 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10069 WHERE `menu_id`=6207 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10071 WHERE `menu_id`=6207 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10073 WHERE `menu_id`=6207 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10110, `option_text`='The Darkmoon Faire has already arrived, you say?  Where is it located?' WHERE `menu_id`=6213 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10647 WHERE `menu_id`=6525 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10821 WHERE `menu_id`=6537 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10820 WHERE `menu_id`=6538 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11934 WHERE `menu_id`=6581 && `id`=0;
UPDATE `broadcast_text` SET `MaleText`='What are these Tonk Control Consoles?', `FemaleText`='What are these Tonk Control Consoles?' WHERE `ID`=11934;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11936 WHERE `menu_id`=6581 && `id`=1;
UPDATE `broadcast_text` SET `MaleText`='Tell me about the cannon.', `FemaleText`='Tell me about the cannon.' WHERE `ID`=11936;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10773 WHERE `menu_id`=6582 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10775 WHERE `menu_id`=6582 && `id`=1;
UPDATE `broadcast_text` SET `MaleText`='What are Darkmoon Faire Prize Tickets and how do I get them?', `FemaleText`='What are Darkmoon Faire Prize Tickets and how do I get them?' WHERE `ID`=10775;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10777 WHERE `menu_id`=6582 && `id`=2;
UPDATE `broadcast_text` SET `MaleText`='What are Darkmoon Cards?', `FemaleText`='What are Darkmoon Cards?' WHERE `ID`=10777;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10779 WHERE `menu_id`=6582 && `id`=3;
UPDATE `broadcast_text` SET `MaleText`='What other things can I do at the faire?', `FemaleText`='What other things can I do at the faire?' WHERE `ID`=10779;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10795 WHERE `menu_id`=6586 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10793 WHERE `menu_id`=6587 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=10791 WHERE `menu_id`=6588 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11336 WHERE `option_text`='What is an Alliance Commendation Signet?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12849 WHERE `menu_id`=6644 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12851 WHERE `menu_id`=6644 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11088 WHERE `menu_id`=6658 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11120 WHERE `menu_id`=6665 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11122 WHERE `menu_id`=6665 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11124 WHERE `menu_id`=6665 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11126 WHERE `menu_id`=6665 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11128 WHERE `menu_id`=6665 && `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11130 WHERE `menu_id`=6665 && `id`=5;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11132 WHERE `option_text`='I want to ask you about something else.';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11120 WHERE `option_text`='What is the Ahn\'Qiraj war effort?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11135 WHERE `menu_id`=6772 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11137 WHERE `menu_id`=6772 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11139 WHERE `menu_id`=6772 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11141 WHERE `menu_id`=6772 && `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11143 WHERE `menu_id`=6772 && `id`=5;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12271 WHERE `menu_id`=6944 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11909 WHERE `menu_id`=7083 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11908 WHERE `menu_id`=7083 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12154 WHERE `menu_id`=7175 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12283 WHERE `menu_id`=8400 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12285 WHERE `menu_id`=8401 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12287 WHERE `menu_id`=8402 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12289 WHERE `menu_id`=8403 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12291 WHERE `menu_id`=8404 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12293 WHERE `menu_id`=8405 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12304 WHERE `menu_id`=8406 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12306 WHERE `menu_id`=8407 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12308 WHERE `menu_id`=8408 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9431 WHERE `menu_id`=10482 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6269 WHERE `menu_id`=10578 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6283 WHERE `menu_id`=10578 && `id`=2;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6284 WHERE `menu_id`=10578 && `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6285 WHERE `menu_id`=10578 && `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6286 WHERE `menu_id`=10578 && `id`=5;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6287 WHERE `menu_id`=10578 && `id`=6;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=6288 WHERE `menu_id`=10578 && `id`=7;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5569 WHERE `menu_id`=12039 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5589 WHERE `menu_id`=12039 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5571 WHERE `menu_id`=12040 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5573 WHERE `menu_id`=12041 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5575 WHERE `menu_id`=12042 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5577 WHERE `menu_id`=12043 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5579 WHERE `menu_id`=12044 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5581 WHERE `menu_id`=12045 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5583 WHERE `menu_id`=12046 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5585 WHERE `menu_id`=12047 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=5587 WHERE `menu_id`=12048 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11016 WHERE `menu_id`=15000 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11034 WHERE `option_text`='How did you know? I mean, yes... Yes I am looking for that shard. Do you have it?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11036 WHERE `menu_id`=15002 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11038, `option_text`='By Bronzbeard\'s... um, beard! What are you talking about?' WHERE `menu_id`=15003 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11040 WHERE `menu_id`=15004 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11042, `option_text`='A minnow? The oceans are filled with minnows! There could be a hundred million minnows out there!' WHERE `menu_id`=15005 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11044 WHERE `menu_id`=15006 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11046 WHERE `menu_id`=15007 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11048 WHERE `menu_id`=15008 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11050 WHERE `menu_id`=15009 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11052 WHERE `menu_id`=15010 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11054, `option_text`='Ok, let me get this straight. You put the scepter shard entrusted to your Flight by Anachronos on a minnow of your own making and now you expect me to build an... an arcanite buoy or something... to force your minnow out of hiding? AND potentially incur the wrath of an Elemental Lord? Did I miss anything? Perhaps I am to do this without any clothes on, during a solar eclipse, on a leap year?\n' WHERE `menu_id`=15011 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11057 WHERE `menu_id`=15012 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11059 WHERE `menu_id`=15013 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11325, `option_text`='I\'m here to retrieve your report.' WHERE `option_text`='May I have your report?';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4474 WHERE `menu_id`=16032 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4476, `option_text`='What happened to him in the first place?  When I... encountered him, he was rather malicious.' WHERE `menu_id`=16033 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4478, `option_text`='I possess part of Eranikus\' essence.  What do you want with it... or with me?' WHERE `menu_id`=16034 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4480 WHERE `menu_id`=16035 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4008 WHERE `option_text`='Use engineering to access hidden schematics!';
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4010 WHERE `menu_id`=20005 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4167 WHERE `menu_id`=20011 && `id`=1;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12481 WHERE `menu_id`=30101 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12483 WHERE `menu_id`=30102 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12485 WHERE `menu_id`=30103 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12487 WHERE `menu_id`=30104 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12489 WHERE `menu_id`=30105 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12491 WHERE `menu_id`=30106 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12493 WHERE `menu_id`=30107 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12495 WHERE `menu_id`=30108 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12497 WHERE `menu_id`=30109 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12499 WHERE `menu_id`=30110 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12501 WHERE `menu_id`=30111 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12503 WHERE `menu_id`=30112 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12505 WHERE `menu_id`=30113 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12507 WHERE `menu_id`=30114 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12509 WHERE `menu_id`=30115 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=12511 WHERE `menu_id`=30116 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9529, `option_text`='Lexlort, I lost the thorium shackles.' WHERE `menu_id`=50406 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=4567, `option_text`='Yes.  Give me the spell to summon the avatar.' WHERE `menu_id`=50408 && `id`=0;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=11350 WHERE `menu_id`=6763 && `id`=0;
UPDATE `broadcast_text` SET `MaleText`='Sprinkle some of the reindeer dust onto Metzen.', `FemaleText`='Sprinkle some of the reindeer dust onto Metzen.' WHERE `ID`=11350;

-- Fix gossip menu id for Stomper Kreeg.
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9373, `option_text`='What do you mean, buy?!  I\'m the king now... and it\'s good to be the king!', `menu_id`=5721 WHERE `menu_id`=10000 && `id`=0;
UPDATE `gossip_menu` SET `entry`=5721 WHERE `entry`=10000;
UPDATE `creature_template` SET `gossip_menu_id`=5721 WHERE `entry`=14322;

-- Fix gossip menu id for Guard Fengus.
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9394, `option_text`='I am, am I?  Well what have you got for the new big dog of Gordok, Fengus?', `menu_id`=5734 WHERE `menu_id`=10001 && `id`=0;
UPDATE `gossip_menu` SET `entry`=5734 WHERE `entry`=10001;
UPDATE `creature_template` SET `gossip_menu_id`=5734 WHERE `entry`=14321;

-- Fix gossip menu id for Guard Slip'kik.
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9398, `option_text`='Yeah, you\'re a real brainiac.  Just how smart do you think you are, Slip\'kik?', `menu_id`=5733 WHERE `menu_id`=10002 && `id`=0;
UPDATE `gossip_menu` SET `entry`=5733 WHERE `entry`=10002;
UPDATE `creature_template` SET `gossip_menu_id`=5733 WHERE `entry`=14323;

-- Fix gossip menu id for Guard Mol'dar.
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9401, `option_text`='Call me "Boss".  What have you got for me!', `menu_id`=5735 WHERE `menu_id`=10003 && `id`=0;
UPDATE `gossip_menu` SET `entry`=5735 WHERE `entry`=10003;
UPDATE `creature_template` SET `gossip_menu_id`=5735 WHERE `entry`=14326;

-- Fix gossip menu id for Captain Kromcrush.
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9421, `option_text`='Um, I\'m taking some prisoners we found outside before the king for punishment.', `menu_id`=5739, `action_menu_id`=5738 WHERE `menu_id`=10004 && `id`=0;
UPDATE `gossip_menu` SET `entry`=5739 WHERE `entry`=10004;
UPDATE `creature_template` SET `gossip_menu_id`=5739 WHERE `entry`=14325;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=9423, `option_text`='Er... that\'s how I found them.  I wanted to show the king that they were a threat!  Say Captain... I overheard Guard Fengus calling you a fat, useless gnoll lover!', `menu_id`=5738 WHERE `menu_id`=10005 && `id`=0;
UPDATE `gossip_menu` SET `entry`=5738 WHERE `entry`=10005;

-- Remove custom npcs with their custom gossip options.
DELETE FROM `creature_template` WHERE `entry` IN (19984, 19995);
DELETE FROM `gossip_menu` WHERE `entry` IN (19998, 19999);
DELETE FROM `gossip_menu_option` WHERE `menu_id` IN (19998, 19999);
DELETE FROM `gossip_scripts` WHERE `id` IN (20017, 20018, 20009, 20005, 20015, 20016, 20020, 20021, 20017, 20018, 20002, 20003, 20004, 20006, 20007, 20008, 20010, 20011, 20012, 20013, 20014, 20000, 20001, 20019);


-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
