DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20200205149300');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20200205149300');
-- Add your query below.

update `locales_quest` set OfferRewardText_loc3="Noch einer der wandelnden Toten, hm? Muss ein ziemlicher Schock gewesen sein, so in der Gruft aufzuwachen, wo es nur Kälte und Mordo gab, um Euch zu begrüßen...$b$bIch sehe Verwirrung in Eurem Gesicht. Lasst mich mal versuchen, Euch unsere... Situation... zu erklären.$b$bWir wurden durch unsere neue Anführerin, Lady Sylvanas, von der Kontrolle durch den Lichkönig befreit. Die dunkle Fürstin führt uns in unserem Krieg gegen die verhasste Geißel und die Bastionen der Menschheit, die jeden unserer Schritte verfolgen." where entry=363;
update `locales_quest` set OfferRewardText_loc3="Es ist schade, dass die Geißel nicht bei uns eingegliedert werden kann, denn ihre große Zahl wäre in den kommenden Schlachten sehr nützlich.$b$bDoch sie werden sich uns nicht anschließen, und daher haben wir keine andere Wahl, als sie zu vernichten." where entry=364;
update `locales_quest` set OfferRewardText_loc3="Ich sprach davon, dass ein Sklave immer ein Sklave bleibt, ungeachtet des Meisters. Erinnert Ihr Euch? Wir beide wissen, dass es diese Art von Kontrolle - diese Art von Macht - ist, die uns jetzt antreibt. Wir wollen, dass uns Kreaturen dienen. Wir wissen, dass wir mächtiger sind und mehr Respekt verdienen als andere uns zollen... Und somit streben wir jetzt danach, uns den Respekt zu nehmen.$b$bIch werde in diesem Kampf Euer Verbündeter sein - im Kampf um unsere eigene Freiheit. Die Freiheit, unsere eigenen Zugehörigkeiten wählen zu können. Wenn Ihr bereit seid, kommt zurück zu mir und ich werde Euch alles lehren, was ich weiß." where entry=3099;
update `locales_quest` set OfferRewardText_loc3="Danke, $N. Diese Rüstung sollte Euch etwas helfen.$b$bHoffentlich hilft sie Euch mehr als ihrem letzten Träger..." where entry=376;
update `locales_quest` set OfferRewardText_loc3="Gute Arbeit, $N, ich wusste, dass Ihr nicht völlig nutzlos seid. Hier, nehmt Euch einen der besseren Gegenstände, die ich aus dem herausgefischt habe, was bisher bereits gesammelt wurde. " where entry=3902;
update `locales_quest` set OfferRewardText_loc3="Ich bin fertig mit Euch, $N. Ihr habt bewiesen, dass Ihr der Freiheit, die Euch gegeben wurde, würdig seid. Viele werden Euch verachten für das, was aus Euch geworden ist. Doch wisset, was auch immer sie versuchen uns anzutun, wir sind frei und werden uns nicht wieder fesseln lassen.$b$bNehmt dies und macht Euch auf den Weg. Es liegt viel Arbeit vor Euch, $C." where entry=3901;
update `locales_quest` set OfferRewardText_loc3="Wenn sie nur auf die Stimme der Vernunft hören würden, hm, $N? Vielleicht könnten wir sie dazu bringen, sich mit uns zu einem vernünftigen Gespräch zusammenzusetzen... ha!$b$bVom Licht geblendete Narren." where entry=381;
update `locales_quest` set OfferRewardText_loc3="Hmm, nun ja, es ist ein Anfang. Es wird ein paar Wochen oder Monate dauern, das Ungeziefer gänzlich auszumerzen. Danach müssen wir mit ein paar Fackeln da runtergehen und die Netze niederbrennen.$b$bIhr habt Eure Pflicht gut erfüllt, $N, und ich bin mir sicher, ich finde noch etwas anderes für Euch zu tun." where entry=380;
update `locales_quest` set OfferRewardText_loc3="Ihr habt heute eine gute Tat vollbracht, $N. Der Kampf gegen die Geißel geht zwar weiter, aber hoffen wir, dass Marla und Samuel gemeinsam Frieden in ihrer letzten Ruhestätte finden." where entry=6395;
update `locales_quest` set OfferRewardText_loc3="Hmmm... Mal sehen, was Ihr da habt...$b$b<Er fängt an, die von Euch beschafften Dokumente durchzublättern.>$b$bNachrichten von ihren Aktionen gegen uns... Wertlos. Spähberichte... Neue Befehle wie 'Baut das Lager nahe der verfallenen Stadt weiter auf...'. Nichts, was wir nicht bereits wüssten... Ah... was haben wir denn hier? Eine Karte, auf der die derzeitigen Posten einiger ihrer Kommandanten und Agenten verzeichnet sind. Damit lässt sich etwas anfangen." where entry=382;
update `locales_quest` set OfferRewardText_loc3="Was ist denn das? Düsterkraut?! Ich brauche kein Düsterkraut! Diese hirnlose Fleischmasse pflückt da draußen Gänseblümchen und bringt Gott weiß wie viele Tölpel wie Euch dazu, das Gleiche zu tun. Das sollte keine Beleidigung sein.$b$bNun denn, Ihr seid jetzt hier und das ist das einzig Wichtige. Da ich keine Zeit darauf verschwenden werde, dieser Monstrosität alles noch mal zu erklären, wie wäre es, wenn Ihr das sammelt, was ich wirklich benötige ... Verdammniskraut." where entry=5481;
update `locales_quest` set OfferRewardText_loc3="Ach? Ein Brief? Wie schön! Ich warte schon seit langem darauf, wieder einmal etwas von meiner lieben alten Mutter in Deathknell zu hören. Sie ist ja eine so wunderbare Person! Ich frage mich, wie die Gute so zurechtkommt.$b$bWas? Zu fröhlich? Ihr kauft mir das nicht ab, wie?$b$bNa, dann verschwindet. Es geht Euch sowieso rein gar nichts an, von wem dieser Brief ist. Na los! Verschwindet schon!$b$bKommt wieder, sobald Ihr 'n bisschen Geld habt, das Ihr ausgeben könnt, Faulenzer.$b$bSonst kommt Ihr als Nächstes noch her und wollt Euch nach einem langen Tag des Abenteuerns hier ausruhen oder so'n Quark." where entry=8;
update `locales_quest` set OfferRewardText_loc3="Unglaublich! Was für ein Talent!$b$bIch dachte, Ihr wärt eine leichte Beute, $N. Habt mich gut geschlagen.$b$bHier das Geld, das ich versprochen habe... nicht so viel, wie ich eigentlich sagte. Das kommt daher, dass ich damals schon gelogen hab." where entry=590;
update `locales_quest` set OfferRewardText_loc3="Ja, das ist sehr gut. Diese Informationen zu beschaffen, war gute Arbeit, $N. Hmm... Die Namen der Offiziere in Tirisfal...$b$bStellt Euch nur vor, welchen Schlag wir der Moral dieser verfluchten Fanatiker verpassen könnten, wenn wir es schaffen, all ihre Anführer auf einen Schlag zu töten." where entry=383;
update `locales_quest` set OfferRewardText_loc3="Ah, mein Verdammniskraut. Exzellent!$b$b<Jungapotheker Holland reibt gierig seine Hände aneinander.>$b$bDas passt perfekt. Ihr habt mir, äh, der Fürstin heute einen großen Dienst erwiesen, $N. Wie versprochen ist hier die Belohnung, die Ihr verdient." where entry=5482;
update `locales_quest` set OfferRewardText_loc3="Das habt Ihr gut gemacht, $N, und ich danke Euch für Eure Mühen." where entry=367;
update `locales_quest` set OfferRewardText_loc3="Gut gemacht. Schade, dass ich nicht dabei war, um Euch zuzusehen, wie Ihr diese Untoten zu Brei geschlagen habt. " where entry=404;
update `locales_quest` set OfferRewardText_loc3="Varimathras wäre stolz. Ihr dient Euren Anführern gut, $C. " where entry=374;
update `locales_quest` set OfferRewardText_loc3="Oh... mein armer Thurman! Ich habe ihn angefleht, Agamands Mühlen mit mir und meinem Vater zu verlassen, aber seine Familienbande waren zu stark! Und ich habe es genau gewusst! Ich wusste einfach, dass Brand ihm Böses wollte! Oh, verflucht seien diese Seuche und die Geißel!$b$b<Yvettes Gesicht glättet sich und wird dann kalt.>$b$bAber Selbstvorwürfe sind etwas für die Schwachen. Als eine Verlassene habe ich neue Ziele, und Liebe ist keines davon. Ich danke Euch, dass Ihr diesen Brief überbracht habt, denn ich hatte mich schon gefragt, was mit meiner alten Liebe geschehen war.$b$bDoch dieses Leben ist vorüber. Auf ewig." where entry=361;
update `locales_quest` set OfferRewardText_loc3="Ihr habt Eure Befehle gut ausgeführt, $C. Ihr habt Euch als eine echte Hilfe für die Armee der dunklen Fürstin erwiesen. " where entry=365;
update `locales_quest` set OfferRewardText_loc3="Beim Licht! Endlich etwas zu essen! Süßer, leckerer Kürbis... " where entry=407;
update `locales_quest` set OfferRewardText_loc3="Ich weiß Eure Mühen zu schätzen, $N. Möge Sylvanas Eure Tapferkeit eines Tages anerkennen... " where entry=375;
update `locales_quest` set OfferRewardText_loc3="Wunderbar, $C. Euer Geschick in der Kriegskunst ist nicht zu leugnen." where entry=427;
update `locales_quest` set OfferRewardText_loc3="Mein Buch?!? Also wart Ihr der Dieb, der es stahl!$b$bDoch... was ist das für eine neue Verzauberung darauf... Bethor? Er ist in Lordaeron?$b$bWenn es ihn immer noch gibt, dann konnte er sich vielleicht ebenfalls dem Zugriff des Lichkönigs entziehen... " where entry=366;
update `locales_quest` set OfferRewardText_loc3="Meisterlich erledigt, $N. Die Geißel irrt sich, wenn sie denkt, dass sie diese Leichen gegen uns verwenden könnte, und die Flüssigkeit, die Ihr von den  der Moderfellsklaven gesammelt habt, wird von unseren Apothekern untersucht werden. Vielleicht enthält sie Geheimnisse, die wir gegen sie verwenden können.$b$bWie gesagt, gut gemacht. Aber unser Kampf geht weiter, und dieser Konflikt wird Euch sicher noch mehr Möglichkeiten bieten, den Verlassenen Euren Wert zu beweisen." where entry=358;
update `locales_quest` set OfferRewardText_loc3="Eure Bemühungen im Krieg sind spürbar, $N. Ich werde Euch nicht für etwas Notwendiges danken, aber die Todeswachen von Tirisfal werden sich Eures Namens erinnern. " where entry=426;
update `locales_quest` set OfferRewardText_loc3="Ah, Ihr seid der Agent, den Magistrat Sevren schickt. Also sind Eure Geschäfte mit mir tatsächlich wichtig.$b$bIch gehe davon aus, dass Sevren jemanden ausgewählt hat, der meiner Aufgabe gewachsen ist... aber wir werden sehen." where entry=405;
update `locales_quest` set OfferRewardText_loc3="Perrines Tod wird die dunkle Fürstin zweifelsohne zufrieden stellen. Ihr habt Eure Befehle gut ausgeführt, $C." where entry=370;
update `locales_quest` set OfferRewardText_loc3="Die Schuppen sind perfekt, $N. Genau das, was ich für dieses Gebräu brauche." where entry=368;
update `locales_quest` set OfferRewardText_loc3="Magistrat Sevren will einen Bericht? Nun gut: Die Verteidiger auf dem Bollwerk halten den Großteil der Geißel in Schach, aber gelegentlich schlüpfen ein paar durch.$b$bWir haben sporadisch Aktivitäten der Geißel östlich dieses Postens gesichtet, und diese häufen sich um Balnirs Bauernhof." where entry=359;
update `locales_quest` set OfferRewardText_loc3="Es ist beunruhigend zu hören, dass die Geißel am Bollwerk vorbeischlüpft. Der Lichkönig und seine Diener greifen uns unaufhörlich an.$b$bAber wir werden nicht nachgeben. Er wird nicht noch einmal von uns Besitz ergreifen!" where entry=360;
update `locales_quest` set OfferRewardText_loc3="Danke. Devlins Knochen werden eine gute Trophäe abgeben.$b$bWenn mein kaltes Herz überhaupt Wärme finden kann, dann in dem Wissen, dass die Agamands vernichtet sind. Sie haben mich und meine Familie im Stich gelassen, als die Seuche kam - jetzt schwöre ich, dass ich ihre Überreste unter meiner Sohle zermalmen werde! " where entry=362;
update `locales_quest` set OfferRewardText_loc3="Captain Vachons Tod wird den Vormarsch des Scharlachroten Kreuzzugs in Tirisfal deutlich verlangsamen. Aber es lauern noch andere Gefahren." where entry=371;
update `locales_quest` set OfferRewardText_loc3="Madenauges abscheuliche Taten wurden endlich gerächt. Vielleicht sind Eure mutigen Taten eine klare Botschaft an die, die unserem Volk Leid zufügen wollen. Ich danke Euch im Namen der Stadt Brill, $N." where entry=398;
update `locales_quest` set OfferRewardText_loc3="Ah, wie zuvorkommend von Apotheker Johaan, mir seine Nachforschungen zu schicken. Dank der ganzen jüngsten Entwicklungen hier im Silberwald hätte ich beinahe die Erkenntnisse vergessen, die aus Lordaeron und Tirisfal kommen. Das erinnert mich daran, dass ich diese Proben umgehend zur Nekropole losschicken muss.$b$bIhr müsst meine Abschweifungen entschuldigen. Verlängert Euren Aufenthalt im Silberwald ein wenig, $N. Ein kräftiger $C wie Ihr wäre hier durchaus von Nutzen." where entry=445;
update `locales_quest` set OfferRewardText_loc3="Ihr schnappt Euch eine der Kerzen und verstaut sie in Eurem Rucksack." where entry=431;
update `locales_quest` set OfferRewardText_loc3="Coleman erzählt Gutes über Euch, $N, wenn er von Euren erfolgreichen Vorstößen in Agamands Mühlen spricht.$b$bDie Verlassenen brauchen Eure Talente erneut..." where entry=355;
update `locales_quest` set OfferRewardText_loc3="Ihr platziert die Kerze des Heranlockens auf dem Tisch und entzündet sie..." where entry=410;
update `locales_quest` set OfferRewardText_loc3="Rache hat einen süßen Geschmack, findet Ihr nicht? Als Ihr die Agamands vernichtet habt, habt Ihr da irgendeinen Hinweis auf einen freien Willen in ihnen bemerkt? Ich hoffe es. Ich hoffe, sie hatten Angst, bevor sie in die Vergessenheit zerschlagen wurden.$b$bDas ist eine närrische Hoffnung, ich weiß. Aber es ist dennoch eine Hoffnung, die ich hege." where entry=354;
update `locales_quest` set OfferRewardText_loc3="Ah, dieses Gift wird genau richtig sein, $N. Alles andere wurde bereits mit meinem Gebräu verkocht. Jetzt bin ich endlich so weit, diesen neuen tödlichen Erreger auszuprobieren! " where entry=369;
update `locales_quest` set OfferRewardText_loc3="Sehr gut. Eure Anstrengungen helfen sehr dabei, die Geißel in Schach zu halten. Meinem Vorgesetzten, Exekutor Zygand, wird eine Empfehlung zugehen." where entry=356;
update `locales_quest` set OfferRewardText_loc3="Ah, endlich, etwas zu trinken. Das ist zwar sicherlich kein Rhapsody-Malz, aber zum jetzigen Zeitpunkt ist mir alles recht, um meine Kehle anzufeuchten." where entry=492;
update `locales_quest` set OfferRewardText_loc3="Das habt Ihr sehr gut gemacht, $C. Dank unnachgiebiger Krieger wie Euch, die im Namen der Verlassenen Siege davontragen, ist unser Volk einen Schritt näher dran, Arthas ein für alle Mal zu besiegen. Ich habe ein gutes Gefühl bei Euch, Kamerad. " where entry=372;
update `locales_quest` set OfferRewardText_loc3="Ihr habt ihn dazu gebracht, sich uns anzuschließen! Ihr habt den Verlassenen einen großen Dienst erwiesen, $N. Die dunkle Fürstin wird das erfahren. " where entry=411;
update `locales_quest` set OfferRewardText_loc3="Ihr habt Lillith Nefara getötet und damit bewiesen, dass Ihr ein Feind der Geißel seid. Unglaublich.$b$bIch glaubte, der einzige Untote mit freiem Willen zu sein, aber Ihr habt mir gezeigt, dass es andere gibt, die der Kontrolle des Lichkönigs getrotzt haben." where entry=409;
update `locales_quest` set OfferRewardText_loc3="Eure Taten verpassten der Geißel einen merklichen Schlag. Und Euer Sieg wird nicht unbemerkt bleiben - weder von den Verlassenen, noch von unseren Feinden.$b$bKämpft weiter, wie wir alle, $N, und eines Tages werden wir den Lichkönig daselbst aus Azeroth vertreiben! " where entry=408;
update `locales_quest` set OfferRewardText_loc3="Die sind prima, $N. Danke.$b$bWenn Ihr bereit seid, können wir uns dem nächsten Schritt zuwenden. " where entry=5901;
update `locales_quest` set OfferRewardText_loc3="Die Termiten werden offensichtlich unruhig, als Ihr das Fass auf die Kiste stellt." where entry=5902;
update `locales_quest` set OfferRewardText_loc3="Ich werde hier sein, Euch zu lehren, während Ihr an Erfahrung gewinnt... sucht mich so oft auf, wie Ihr mögt. Ich verlange eine minimale Gebühr, Ihr werdet jedoch alles, was ich Euch lehren kann, lohnenswert finden.$b$bGeht jetzt und prüft Eure Fertigkeiten. Während Ihr an Erfahrung gewinnt, werden sich Euch viele neue Dinge offenbaren; einige davon kann ich hier jetzt nicht mit Euch besprechen. Wisset nur, dass Sylvanas künftig $C mit Kraft wie Euresgleichen brauchen wird. Ihr werdet das Rückgrat unserer Rettung sein. Vergesst das nicht." where entry=3095;
update `locales_quest` set OfferRewardText_loc3="Ich habe die meiste Zeit hier im Gasthaus verbracht, auf neue Gesichter geachtet und nach möglichen künftigen Aspiranten Ausschau gehalten. Haltet die Nase frei und ich tue, was ich kann, um Euch einige Dinge zu lehren. Kommt einfach zu mir zurück, wann immer Ihr wollt und wir werden sehen, ob Ihr bereit seid für eine neue Fertigkeit oder zwei." where entry=3096;
update `locales_quest` set OfferRewardText_loc3="Hm. Ihr seid zweifellos in dem Augenblick hierher gekommen, als Ihr meinen Ruf vernommen habt, nicht? Natürlich. Von einem angehenden Todespirscher hätte ich nichts anderes erwartet." where entry=1885;
update `locales_quest` set OfferRewardText_loc3="Hmm, das ist interessant. Die Todespirscher haben ihre Pflicht bei der Erledigung dieser Aufgabe meisterlich erfüllt.$b$bSoweit ich informiert bin, verdient Ihr ebenfalls Lob für Eure Leistung. Ich hoffe, dass das bei Euch zur Gewohnheit wird, $N, meine Todespirscher haben immer Verwendung für gute Männer." where entry=1978;
update `locales_quest` set OfferRewardText_loc3="Das sind eindeutig mehr Informationen, als ich mir je von Andron erhofft hätte. Lasst sie mich einen Moment studieren, bevor ich Euch Eure nächste Aufgabe nenne." where entry=1899;
update `locales_quest` set OfferRewardText_loc3="Ah, ja, ich habe Euch erwartet. Ich darf davon ausgehen, dass unsere gemeinsamen Bekannten mit den Informationen, die ich bisher lieferte, zufrieden waren?$b$bVermutlich hat es keinen Sinn, Euch zu fragen. Ich bezweifle, dass sie Euch mit diesem Wissen belasten würden. Warum so viel Vertrauen in den Boten setzen, hm?" where entry=1898;
update `locales_quest` set OfferRewardText_loc3="Ihr habt Eure Sache gut gemacht, $N. Mir fällt ein, dass Ihr den Todespirschern viele Dienste geleistet und damit Euren Wert bewiesen habt. Vielleicht ist es an der Zeit, dass wir Eure Ausbildung in den Schattenkünsten fortsetzen." where entry=1998;
update `locales_quest` set OfferRewardText_loc3="Gut gemacht, $N. Ulag war kein unmaßgeblicher Agent der Geißel. Ihr habt den Todeswachen, und damit der dunklen Fürstin, gezeigt, dass Ihr ein geschickter und entschlossener $C seid, und Euch damit weitere Ausbildung verdient." where entry=1819;
update `locales_quest` set OfferRewardText_loc3="Seid Ihr wegen einer Mission hier? Gut. Ich habe eine wichtige, die Eure Fertigkeiten im Gefecht auf die Probe stellt... und Eure Entschlossenheit, die Verlassenen zu verteidigen." where entry=1818;
update `locales_quest` set OfferRewardText_loc3="Ah! Ihr habt sie genommen! Jetzt ist das letzte Restchen Ehre und Andenken vom verfluchten Land der Agamands entfernt. Die Familie existiert wahrlich nicht mehr!" where entry=1821;
update `locales_quest` set OfferRewardText_loc3="Ich behalte drei der Waffen, die Ihr mir gebracht habt, als Andenken an meinen Schmerz und Verlust. Aber bitte, $N, wählt Euer Lieblingserbstück und behaltet es für Euch.$b$bMöge es Euch besser dienen als seinen verfluchten vorherigen Besitzern." where entry=1822;
update `locales_quest` set OfferRewardText_loc3="Das hier ist nicht der Ort für Euch, $N. Ihr solltet Euch so bald wie möglich zum Kriegsviertel nach Unterstadt begeben. Aelthalyste hat alle ihre Priester und Priesterinnen dort zusammengerufen, sobald sie bereit sind. Es ist an der Zeit, dass sie mehr über ihre Macht lernen, und darüber, wie sie zu nutzen ist.$b$bSie wird weder Zuspätkommen noch Entschuldigungen tolerieren, also solltet Ihr Euch auf den Weg machen." where entry=5659;
update `locales_quest` set OfferRewardText_loc3="Ihr müsst nur eins wissen: Wir haben durch schiere Willenskraft überlebt. Es ist der Glaube an uns selbst, der uns von anderen unterscheidet, und mit unserer Macht werden wir große Veränderungen in gesamt Azeroth herbeiführen. Die Schwachen werden auf Euch angewiesen sein. Die Leprakranken werden Euch Lord nennen. Und die Ignoranten werden Euch um Führung ersuchen. Es ist meine Pflicht sicherzustellen, dass Ihr die nötigen Werkzeuge habt, sodass Ihr bereit seid, wenn die Zeit gekommen ist. Sucht mich auf, während Ihr an Erfahrung gewinnt. Ich werde Euch lehren, wie Ihr noch mächtiger werdet, wenn Ihr dazu bereit seid." where entry=3097;
update `locales_quest` set OfferRewardText_loc3="Ihr habt meine Prüfung mit Leichtigkeit bestanden. Gut.$b$bBald werdet Ihr bereit sein, mehr Verantwortung zu übernehmen, und dieser Weg wird Euch zu dunkleren Kräften führen... Kräfte, die kein $C eines anderen Volkes besitzt.$b$bNehmt diese Robe als Symbol Eures Standes. Ihr habt sie Euch verdient. Wenn Ihr sie nicht tragen wollt, dann sei es so, Ihr könnt damit tun, was Ihr wollt. Ich und andere wie wir werden Euch immer Anerkennung dafür zollen, was Ihr in unseren Reihen erreicht habt." where entry=5650;
update `locales_quest` set OfferRewardText_loc3="Ah, junger $C, ich bin froh, dass Ihr hierher zurückgekehrt seid. Ich würde Euch gerne eine Lektion lehren, die Ihr besser nicht vergessen solltet. Seid Ihr bereit?" where entry=5658;
update `locales_quest` set OfferRewardText_loc3="Endlich seid Ihr da. Euer Glaube allein wird Euch nicht helfen, die Aufgaben zu bewältigen, die vor Euch liegen. Etwas Dringlichkeit und ein wenig Ehrgeiz helfen auch." where entry=5651;
update `locales_quest` set OfferRewardText_loc3="Ihr müsst oft zu mir zurückkehren, wenn Ihr mächtig genug werden wollt, um unsere Gegner zu vernichten. Die Regeln der Magie gelten noch immer für Euch, $N. Ihr werdet noch immer feststellen, dass Euch die Verderbnis folgt, wie hungrige Wölfe in der Nacht. Ihr werdet ihre sanften Berührungen fühlen und feststellen, dass sie einer Sucht ähnelt, einem alten Liebhaber, dem es noch immer verlangt, an Eurer Seite zu sein. Ihr könnt diese Dinge jedoch abschütteln. Diese Dinge werden Euch nur kontrollieren, wenn Ihr dies zulasst.$b$bGeht jetzt und kehrt zurück, wenn Ihr mächtiger geworden seid." where entry=3098;

-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;