DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20221210185328');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20221210185328');
-- Add your query below.


-- Night Watch Guards were level 40 prior to patch 1.7.
-- https://github.com/vmangos/core/issues/1731
DELETE FROM `creature_template` WHERE `entry`=10038;
INSERT INTO `creature_template` (`entry`, `patch`, `display_id1`, `display_id2`, `display_id3`, `display_id4`, `display_scale1`, `display_scale2`, `display_scale3`, `display_scale4`, `display_probability1`, `display_probability2`, `display_probability3`, `display_probability4`, `display_total_probability`, `mount_display_id`, `name`, `subname`, `gossip_menu_id`, `level_min`, `level_max`, `faction`, `npc_flags`, `speed_walk`, `speed_run`, `detection_range`, `call_for_help_range`, `leash_range`, `rank`, `xp_multiplier`, `health_multiplier`, `mana_multiplier`, `armor_multiplier`, `damage_multiplier`, `damage_variance`, `damage_school`, `base_attack_time`, `ranged_attack_time`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `unit_class`, `unit_flags`, `pet_family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `loot_id`, `pickpocket_loot_id`, `skinning_loot_id`, `gold_min`, `gold_max`, `spell_id1`, `spell_id2`, `spell_id3`, `spell_id4`, `spell_list_id`, `pet_spell_list_id`, `spawn_spell_id`, `auras`, `ai_name`, `movement_type`, `inhabit_type`, `civilian`, `racial_leader`, `regeneration`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `school_immune_mask`, `flags_extra`, `script_name`) VALUES (10038, 0, 2381, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 'Night Watch Guard', 'The Night Watch', 0, 40, 40, 56, 0, 1, 1.42857, 18, 5, 0, 0, 1, 2, 1, 0.6, 3.25, 0.14, 0, 2000, 2000, 0, 0, 0, 0, 0, 10, 1, 4112, 0, 0, 0, 0, 0, 7, 0, 10038, 0, 0, 213, 213, 0, 0, 0, 0, 0, 0, 0, NULL, '', 0, 3, 0, 0, 3, 10038, 0, 0, 0, 0, 525312, '');
INSERT INTO `creature_template` (`entry`, `patch`, `display_id1`, `display_id2`, `display_id3`, `display_id4`, `display_scale1`, `display_scale2`, `display_scale3`, `display_scale4`, `display_probability1`, `display_probability2`, `display_probability3`, `display_probability4`, `display_total_probability`, `mount_display_id`, `name`, `subname`, `gossip_menu_id`, `level_min`, `level_max`, `faction`, `npc_flags`, `speed_walk`, `speed_run`, `detection_range`, `call_for_help_range`, `leash_range`, `rank`, `xp_multiplier`, `health_multiplier`, `mana_multiplier`, `armor_multiplier`, `damage_multiplier`, `damage_variance`, `damage_school`, `base_attack_time`, `ranged_attack_time`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `unit_class`, `unit_flags`, `pet_family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `loot_id`, `pickpocket_loot_id`, `skinning_loot_id`, `gold_min`, `gold_max`, `spell_id1`, `spell_id2`, `spell_id3`, `spell_id4`, `spell_list_id`, `pet_spell_list_id`, `spawn_spell_id`, `auras`, `ai_name`, `movement_type`, `inhabit_type`, `civilian`, `racial_leader`, `regeneration`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `school_immune_mask`, `flags_extra`, `script_name`) VALUES (10038, 5, 2381, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 'Night Watch Guard', 'The Night Watch', 0, 55, 55, 56, 0, 1, 1.42857, 18, 5, 0, 0, 1, 2, 1, 0.6, 3.25, 0.14, 0, 2000, 2000, 0, 0, 0, 0, 0, 10, 1, 4112, 0, 0, 0, 0, 0, 7, 0, 10038, 0, 0, 213, 213, 0, 0, 0, 0, 0, 0, 0, NULL, '', 0, 3, 0, 0, 3, 10038, 0, 0, 0, 0, 525312, '');

-- Southshore Guard were level 50 prior to patch 1.7.
-- https://github.com/vmangos/core/issues/1730
DELETE FROM `creature_template` WHERE `entry`=2386;
INSERT INTO `creature_template` (`entry`, `patch`, `display_id1`, `display_id2`, `display_id3`, `display_id4`, `display_scale1`, `display_scale2`, `display_scale3`, `display_scale4`, `display_probability1`, `display_probability2`, `display_probability3`, `display_probability4`, `display_total_probability`, `mount_display_id`, `name`, `subname`, `gossip_menu_id`, `level_min`, `level_max`, `faction`, `npc_flags`, `speed_walk`, `speed_run`, `detection_range`, `call_for_help_range`, `leash_range`, `rank`, `xp_multiplier`, `health_multiplier`, `mana_multiplier`, `armor_multiplier`, `damage_multiplier`, `damage_variance`, `damage_school`, `base_attack_time`, `ranged_attack_time`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `unit_class`, `unit_flags`, `pet_family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `loot_id`, `pickpocket_loot_id`, `skinning_loot_id`, `gold_min`, `gold_max`, `spell_id1`, `spell_id2`, `spell_id3`, `spell_id4`, `spell_list_id`, `pet_spell_list_id`, `spawn_spell_id`, `auras`, `ai_name`, `movement_type`, `inhabit_type`, `civilian`, `racial_leader`, `regeneration`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `school_immune_mask`, `flags_extra`, `script_name`) VALUES (2386, 0, 3705, 3708, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 'Southshore Guard', NULL, 0, 50, 50, 11, 0, 1, 1.42857, 18, 5, 0, 0, 1, 1.25, 1, 0.95, 1.3, 0.14, 0, 2000, 2000, 0, 0, 0, 0, 0, 0, 1, 4096, 0, 0, 0, 0, 0, 7, 0, 2386, 2386, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'EventAI', 0, 3, 0, 0, 3, 2386, 0, 0, 0, 0, 525312, '');
INSERT INTO `creature_template` (`entry`, `patch`, `display_id1`, `display_id2`, `display_id3`, `display_id4`, `display_scale1`, `display_scale2`, `display_scale3`, `display_scale4`, `display_probability1`, `display_probability2`, `display_probability3`, `display_probability4`, `display_total_probability`, `mount_display_id`, `name`, `subname`, `gossip_menu_id`, `level_min`, `level_max`, `faction`, `npc_flags`, `speed_walk`, `speed_run`, `detection_range`, `call_for_help_range`, `leash_range`, `rank`, `xp_multiplier`, `health_multiplier`, `mana_multiplier`, `armor_multiplier`, `damage_multiplier`, `damage_variance`, `damage_school`, `base_attack_time`, `ranged_attack_time`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `unit_class`, `unit_flags`, `pet_family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `loot_id`, `pickpocket_loot_id`, `skinning_loot_id`, `gold_min`, `gold_max`, `spell_id1`, `spell_id2`, `spell_id3`, `spell_id4`, `spell_list_id`, `pet_spell_list_id`, `spawn_spell_id`, `auras`, `ai_name`, `movement_type`, `inhabit_type`, `civilian`, `racial_leader`, `regeneration`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `school_immune_mask`, `flags_extra`, `script_name`) VALUES (2386, 5, 3705, 3708, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 'Southshore Guard', NULL, 0, 55, 55, 11, 0, 1, 1.42857, 18, 5, 0, 0, 1, 1.25, 1, 0.95, 1.3, 0.14, 0, 2000, 2000, 0, 0, 0, 0, 0, 0, 1, 4096, 0, 0, 0, 0, 0, 7, 0, 2386, 2386, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'EventAI', 0, 3, 0, 0, 3, 2386, 0, 0, 0, 0, 525312, '');

-- Tarren Mill Deathguard were level 50 prior to patch 1.7.
-- https://github.com/vmangos/core/issues/1730
DELETE FROM `creature_template` WHERE `entry`=2405;
INSERT INTO `creature_template` (`entry`, `patch`, `display_id1`, `display_id2`, `display_id3`, `display_id4`, `display_scale1`, `display_scale2`, `display_scale3`, `display_scale4`, `display_probability1`, `display_probability2`, `display_probability3`, `display_probability4`, `display_total_probability`, `mount_display_id`, `name`, `subname`, `gossip_menu_id`, `level_min`, `level_max`, `faction`, `npc_flags`, `speed_walk`, `speed_run`, `detection_range`, `call_for_help_range`, `leash_range`, `rank`, `xp_multiplier`, `health_multiplier`, `mana_multiplier`, `armor_multiplier`, `damage_multiplier`, `damage_variance`, `damage_school`, `base_attack_time`, `ranged_attack_time`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `unit_class`, `unit_flags`, `pet_family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `loot_id`, `pickpocket_loot_id`, `skinning_loot_id`, `gold_min`, `gold_max`, `spell_id1`, `spell_id2`, `spell_id3`, `spell_id4`, `spell_list_id`, `pet_spell_list_id`, `spawn_spell_id`, `auras`, `ai_name`, `movement_type`, `inhabit_type`, `civilian`, `racial_leader`, `regeneration`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `school_immune_mask`, `flags_extra`, `script_name`) VALUES (2405, 0, 3662, 3663, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 'Tarren Mill Deathguard', NULL, 0, 50, 50, 71, 0, 1, 1.14286, 18, 5, 0, 0, 1, 2, 1, 1.2, 2, 0.14, 0, 2000, 2000, 0, 0, 0, 0, 0, 0, 1, 4096, 0, 0, 0, 0, 0, 7, 0, 0, 2405, 0, 0, 0, 0, 0, 0, 0, 24050, 0, 0, NULL, 'EventAI', 1, 3, 0, 0, 3, 2405, 0, 0, 0, 0, 525312, '');
INSERT INTO `creature_template` (`entry`, `patch`, `display_id1`, `display_id2`, `display_id3`, `display_id4`, `display_scale1`, `display_scale2`, `display_scale3`, `display_scale4`, `display_probability1`, `display_probability2`, `display_probability3`, `display_probability4`, `display_total_probability`, `mount_display_id`, `name`, `subname`, `gossip_menu_id`, `level_min`, `level_max`, `faction`, `npc_flags`, `speed_walk`, `speed_run`, `detection_range`, `call_for_help_range`, `leash_range`, `rank`, `xp_multiplier`, `health_multiplier`, `mana_multiplier`, `armor_multiplier`, `damage_multiplier`, `damage_variance`, `damage_school`, `base_attack_time`, `ranged_attack_time`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `unit_class`, `unit_flags`, `pet_family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `loot_id`, `pickpocket_loot_id`, `skinning_loot_id`, `gold_min`, `gold_max`, `spell_id1`, `spell_id2`, `spell_id3`, `spell_id4`, `spell_list_id`, `pet_spell_list_id`, `spawn_spell_id`, `auras`, `ai_name`, `movement_type`, `inhabit_type`, `civilian`, `racial_leader`, `regeneration`, `equipment_id`, `trainer_id`, `vendor_id`, `mechanic_immune_mask`, `school_immune_mask`, `flags_extra`, `script_name`) VALUES (2405, 5, 3662, 3663, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 'Tarren Mill Deathguard', NULL, 0, 55, 55, 71, 0, 1, 1.14286, 18, 5, 0, 0, 1, 2, 1, 1.2, 2, 0.14, 0, 2000, 2000, 0, 0, 0, 0, 0, 0, 1, 4096, 0, 0, 0, 0, 0, 7, 0, 0, 2405, 0, 0, 0, 0, 0, 0, 0, 24050, 0, 0, NULL, 'EventAI', 1, 3, 0, 0, 3, 2405, 0, 0, 0, 0, 525312, '');


-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
