SET NAMES utf8;
DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20230913145819');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20230913145819');
-- Add your query below.


SET NAMES utf8;
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (2500, 0, 'They\'re out there!  I can hear them at night, laughing.  Oh, they\'ll pay!  They...will...pay!!', '저 밖에 있어요! 밤에 웃는 소리가 들립니다. 아, 지불할 거예요! 그들은... 지불할 것입니다!!', 'Ils sont dehors ! Je peux les entendre la nuit rire. Oh, ils paieront ! Ils... paieront... !!', 'Sie sind da draußen! Ich kann sie nachts lachen hören. Oh, sie werden bezahlen! Sie werden bezahlen!!', '他们就在那里！ 晚上我能听到他们的笑声。 哦，他们会付钱的！ 他们……会……付出代价！', '他們就在那裡！ 晚上我能聽到他們的笑聲。 哦，他們會付錢的！ 他們……會……付出代價！', '¡Están ahí fuera! Puedo oírlos por la noche, riendo. ¡Oh, pagarán! ¡¡Ellos...pagarán!!', NULL, 'Они там! Я слышу их смех по ночам. О, они заплатят! Они... заплатят!!', 0, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (2934, 0, 'Knowledge is both tool and weapon to those with the will to use it.', '지식은 그것을 사용하려는 의지를 가진 사람들에게 도구이자 무기입니다.', 'La connaissance est à la fois un outil et une arme pour ceux qui ont la volonté de l’utiliser.', 'Wissen ist sowohl Werkzeug als auch Waffe für diejenigen, die es nutzen wollen.', '对于那些愿意使用知识的人来说，知识既是工具也是武器。', '對於那些願意使用知識的人來說，知識既是工具也是武器。', 'El conocimiento es a la vez herramienta y arma para quienes tienen la voluntad de utilizarlo.', NULL, 'Знания являются одновременно инструментом и оружием для тех, кто хочет их использовать.', 1, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (4048, 0, 'You look as though you have traveled from afar, $r.', '$r님, 마치 먼 곳에서 여행 온 것 같군요.', 'Vous avez l\'air d\'avoir voyagé de loin, $r.', 'Du siehst aus, als wärst du von weit her gereist, $r.', '你看起来就像是从远方来的一样，$r。', '你看起來就像是從遠方來的一樣，$r。', 'Parece que has viajado desde lejos, $r.', NULL, 'Ты выглядишь так, будто прилетел издалека, $r.', 2, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (5878, 0, 'My vision has darkened, but there are many kinds of sight...', '시력이 어두워졌지만 시력은 여러 가지가 있습니다 ...', 'Ma vision s\'est obscurcie, mais il existe de nombreux types de vision...', 'Meine Sicht hat sich verdunkelt, aber es gibt viele Arten von Sicht ...', '我的视野变暗了，但是视线有很多种……', '我的視野變暗了，但是視線有很多種……', 'Mi visión se ha oscurecido, pero hay muchas clases de visión...', NULL, 'В глазах моём потемнело, но есть много видов зрения...', 0, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (6142, 0, 'The craft of the night elves ranges beyond the woods and its denizens.  We know much of the earth below, and of the metals within it.', '나이트 엘프의 기술은 숲과 그 거주민 너머에까지 미치고 있습니다. 우리는 아래의 지구와 그 안에 있는 금속에 대해 많이 알고 있습니다.', 'L\'artisanat des elfes de la nuit s\'étend au-delà des bois et de leurs habitants. Nous connaissons une grande partie de la terre et des métaux qu’elle contient.', 'Das Handwerk der Nachtelfen reicht über den Wald und seine Bewohner hinaus. Wir wissen viel über die Erde darunter und die Metalle darin.', '暗夜精灵的技艺超出了森林及其居民的范围。 我们对下面的地球及其内部的金属了解很多。', '暗夜精靈的技藝超出了森林及其居民的範圍。 我們對下面的地球及其內部的金屬了解很多。', 'El oficio de los elfos de la noche va más allá de los bosques y sus habitantes. Sabemos mucho de la tierra que hay debajo y de los metales que contiene.', NULL, 'Ремесло ночных эльфов выходит за рамки леса и его обитателей. Мы многое знаем о земле под ней и о металлах, находящихся в ней.', 1, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (6166, 0, 'You think you have guts?  Well I have something for you if you do...', '당신은 용기가 있다고 생각하십니까? 그렇다면 당신에게 드릴 말씀이 있습니다...', 'Tu penses que tu as du cran ? Eh bien, j\'ai quelque chose pour toi si tu le fais...', 'Glaubst du, du hast Mut? Nun, ich habe etwas für dich, wenn du es tust ...', '你觉得你有胆量吗？ 好吧，如果你愿意的话，我有东西给你......', '你覺得你有膽量嗎？ 好吧，如果你願意的話，我有東西給你......', '¿Crees que tienes agallas? Bueno, tengo algo para ti si lo haces...', NULL, 'Думаешь, у тебя есть смелость? Ну, у меня есть кое-что для тебя, если хочешь...', 1, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (11036, 0, 'Through knowledge, may we find salvation.', '지식을 통해 우리가 구원을 찾을 수 있기를 바랍니다.', 'Grâce à la connaissance, puissions-nous trouver le salut.', 'Mögen wir durch Wissen Erlösung finden.', '通过知识，愿我们找到救赎。', '通過知識，願我們找到救贖。', 'Que a través del conocimiento podamos encontrar la salvación.', NULL, 'Через знание да обретем мы спасение.', 1, 0);
INSERT INTO `quest_greeting` (`entry`, `type`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `emote_id`, `emote_delay`) VALUES (14567, 0, 'These Mithril Order guys are sissies.', '이 미스릴 기사단 놈들은 계집애들이야.', 'Ces gars de l’Ordre du Mithril sont des poules mouillées.', 'Diese Jungs vom Mithril-Orden sind Weicheier.', '这些秘银教团的家伙都是胆小鬼。', '這些秘銀教團的傢伙都是膽小鬼。', 'Estos chicos de Mithril Order son unos maricas.', NULL, 'Эти ребята из Мифрилового Ордена - бабы.', 1, 0);


-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
