SET NAMES utf8;
DROP PROCEDURE IF EXISTS add_migration;
delimiter ??
CREATE PROCEDURE `add_migration`()
BEGIN
DECLARE v INT DEFAULT 1;
SET v = (SELECT COUNT(*) FROM `migrations` WHERE `id`='20230502170900');
IF v=0 THEN
INSERT INTO `migrations` VALUES ('20230502170900');
-- Add your query below.


-- Add localization to areatrigger texts.
CREATE TABLE IF NOT EXISTS `locales_areatrigger` (
  `entry` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `message_loc1` varchar(200) NOT NULL DEFAULT '',
  `message_loc2` varchar(200) NOT NULL DEFAULT '',
  `message_loc3` varchar(200) NOT NULL DEFAULT '',
  `message_loc4` varchar(200) NOT NULL DEFAULT '',
  `message_loc5` varchar(200) NOT NULL DEFAULT '',
  `message_loc6` varchar(200) NOT NULL DEFAULT '',
  `message_loc7` varchar(200) NOT NULL DEFAULT '',
  `message_loc8` varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

SET NAMES utf8;
INSERT INTO `locales_areatrigger` (`entry`, `message_loc1`, `message_loc2`, `message_loc3`, `message_loc4`, `message_loc5`, `message_loc6`, `message_loc7`, `message_loc8`) VALUES
(45, '20 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 20 pour entrer.', 'Ihr müsst mindestens Stufe 20 sein, um eintreten zu können.', '只有至少20级的玩家才能进入。', '只有20級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 20.', 'Debes tener al menos nivel 20 para entrar.', 'Сюда допускаются только персонажи, достигшие 20 уровня.'),
(78, '10 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 10 pour entrer.', 'Ihr müsst mindestens Stufe 10 sein, um eintreten zu können.', '只有至少10级的玩家才能进入。', '只有10級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 10.', 'Debes tener al menos nivel 10 para entrar.', 'Сюда допускаются только персонажи, достигшие 10 уровня.'),
(101, '15 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 15 pour entrer', 'Ihr müsst mindestens Stufe 15 sein, um eintreten zu können.', '只有至少15级的玩家才能进入。', '只有15級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 15.', 'Debes tener al menos nivel 15 para entrar.', 'Сюда допускаются только персонажи, достигшие 15 уровня.'),
(145, '10 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 10 pour entrer', 'Ihr müsst mindestens Stufe 10 sein, um eintreten zu können.', '只有至少10级的玩家才能进入。', '只有10級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 10.', 'Debes tener al menos nivel 10 para entrar.', 'Сюда допускаются только персонажи, достигшие 10 уровня.'),
(228, '10 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 10 pour entrer.', 'Ihr müsst mindestens Stufe 10 sein, um eintreten zu können.', '只有至少10级的玩家才能进入。', '只有10級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 10.', 'Debes tener al menos nivel 10 para entrar.', 'Сюда допускаются только персонажи, достигшие 10 уровня.'),
(244, '15 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 15 pour entrer.', 'Ihr müsst mindestens Stufe 15 sein, um eintreten zu können.', '只有至少15级的玩家才能进入。', '只有15級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 15.', 'Debes tener al menos nivel 15 para entrar.', 'Сюда допускаются только персонажи, достигшие 15 уровня.'),
(257, '10 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 10 pour entrer', 'Ihr müsst mindestens Stufe 10 sein, um eintreten zu können.', '只有至少10级的玩家才能进入。', '只有10級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 10.', 'Debes tener al menos nivel 10 para entrar.', 'Сюда допускаются только персонажи, достигшие 10 уровня.'),
(286, '30 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 30 pour entrer.', 'Ihr müsst mindestens Stufe 30 sein, um eintreten zu können.', '只有至少30级的玩家才能进入。', '只有30級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 30.', 'Debes tener al menos nivel 30 para entrar.', 'Сюда допускаются только персонажи, достигшие 30 уровня.'),
(324, '15 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 15 pour entrer.', 'Ihr müsst mindestens Stufe 15 sein, um eintreten zu können.', '只有至少15级的玩家才能进入。', '只有15級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 15.', 'Debes tener al menos nivel 15 para entrar.', 'Сюда допускаются только персонажи, достигшие 15 уровня.'),
(442, '25 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 25 pour entrer.', 'Ihr müsst mindestens Stufe 25 sein, um eintreten zu können.', '只有至少25级的玩家才能进入。', '只有25級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 25.', 'Debes tener al menos nivel 25 para entrar.', 'Сюда допускаются только персонажи, достигшие 25 уровня.'),
(446, '35 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 35 pour entrer.', 'Ihr müsst mindestens Stufe 35 sein, um eintreten zu können.', '只有至少35级的玩家才能进入。', '只有35級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 35.', 'Debes tener al menos nivel 35 para entrar.', 'Сюда допускаются только персонажи, достигшие 35 уровня.'),
(523, '15 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 15 pour entrer', 'Ihr müsst mindestens Stufe 15 sein, um eintreten zu können.', '只有至少15级的玩家才能进入。', '只有15級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 15.', 'Debes tener al menos nivel 15 para entrar.', 'Сюда допускаются только персонажи, достигшие 15 уровня.'),
(610, '20 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 20 pour entrer.', 'Ihr müsst mindestens Stufe 20 sein, um eintreten zu können.', '只有至少20级的玩家才能进入。', '只有20級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 20.', 'Debes tener al menos nivel 20 para entrar.', 'Сюда допускаются только персонажи, достигшие 20 уровня.'),
(612, '20 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 20 pour entrer.', 'Ihr müsst mindestens Stufe 20 sein, um eintreten zu können.', '只有至少20级的玩家才能进入。', '只有20級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 20.', 'Debes tener al menos nivel 20 para entrar.', 'Сюда допускаются только персонажи, достигшие 20 уровня.'),
(614, '20 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 20 pour entrer.', 'Ihr müsst mindestens Stufe 20 sein, um eintreten zu können.', '只有至少20级的玩家才能进入。', '只有20級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 20.', 'Debes tener al menos nivel 20 para entrar.', 'Сюда допускаются только персонажи, достигшие 20 уровня.'),
(902, '30 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 30 pour entrer', 'Ihr müsst mindestens Stufe 30 sein, um eintreten zu können.', '只有至少30级的玩家才能进入。', '只有30級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 30.', 'Debes tener al menos nivel 30 para entrar.', 'Сюда допускаются только персонажи, достигшие 30 уровня.'),
(924, '35 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 35 pour entrer.', 'Ihr müsst mindestens Stufe 35 sein, um eintreten zu können.', '只有至少35级的玩家才能进入。', '只有35級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 35.', 'Debes tener al menos nivel 35 para entrar.', 'Сюда допускаются только персонажи, достигшие 35 уровня.'),
(1466, '40 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 40 pour entrer.', 'Ihr müsst mindestens Stufe 40 sein, um eintreten zu können.', '只有至少40级的玩家才能进入。', '只有40級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 40.', 'Debes tener al menos nivel 40 para entrar.', 'Сюда допускаются только персонажи, достигшие 40 уровня.'),
(1468, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(2214, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(2216, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(2217, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(2230, '8 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 8 pour entrer', 'Ihr müsst mindestens Stufe 8 sein, um eintreten zu können.', '只有至少8级的玩家才能进入。', '只有8級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 8.', 'Debes tener al menos nivel 8 para entrar.', 'Сюда допускаются только персонажи, достигшие 8 уровня.'),
(2527, '전설의 전당을 이용하려면 투사 계급 이상이 되어야 합니다.', 'Vous devez être un Garde de pierre ou supérieur pour entrer dans le Hall des légendes.', 'Ihr müsst den Rang \'Steingardist\' oder höher erreicht haben, um die Halle der Legenden betreten zu dürfen.', '你必须拥有石头守卫或更高级别的军衔才能进入传说大厅。', '你必須擁有石頭守衛或更高級別的軍銜才能進入傳說大廳。', 'Para entrar a la Sala de las Leyendas, debes tener rango de Guardia de piedra o superior.', 'Debes ser Guardia de piedra o de rango superior para ingresar a la Sala de las Leyendas.', 'Зал Легенд открыт только для Каменных Стражей или обладателей более высокого ранга.'),
(2532, '용사의 전당을 이용하려면 기사 계급 이상이 되어야 합니다.', 'Vous devez être au moins Chevalier pour entrer dans le Hall des Champions.', 'Ihr müsst den Rang \'Leutnant\' oder höher erreicht haben, um die Halle der Champions betreten zu dürfen.', '你必须拥有骑士或更高级别的军衔才能进入勇士大厅。', '你必須擁有騎士或更高級別的軍銜才能進入傳說大廳。', 'Para entrar a la Sala de los Campeones, debes tener rango de Caballero o superior.', 'Debes ser Caballero o de rango superior para ingresar a la Sala de los Campeones.', 'Зал Защитников открыт только для рыцарей или обладателей более высокого ранга.'),
(2567, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(2606, '호드 일원만 진입할 수 있습니다.', 'Seule la Horde peut utiliser ce portail.', 'Nur die Horde kann dieses Portal benutzen.', '只有部落可以使用这个传送门。', '只有部落可以使用這個傳送門。', 'Solo la Horda puede utilizar este portal.', 'Solo la Horda puede utilizar este portal.', 'Этот портал открыт только для подданных Орды.'),
(2608, '얼라이언스 일원만 진입할 수 있습니다.', 'Seule l\'Alliance peut utiliser ce portail.', 'Nur die Allianz kann dieses Portal benutzen.', '只有联盟可以使用这个传送门。', '只有聯盟可以使用這個傳送門。', 'Solo la Alianza puede utilizar este portal.', 'Solo la Alianza puede utilizar este portal.', 'Этот портал открыт только для подданных Альянса.'),
(2848, '공격대에 참여한 후 비룡불꽃 아뮬렛을 소지한 50 레벨 이상만 진입할 수 있습니다.', 'Vous devez faire partie d\'un groupe de raid, être au moins de niveau 50 et posséder dans votre inventaire l\'Amulette drakefeu pour entrer.', 'Ihr müsst zu einer Schlachtgruppe gehören, mindestens Stufe 50 sein und das Drachenfeueramulett in Eurem Inventar haben, um eintreten zu können.', '你必须在一个团队中，等级至少为50级，并在物品栏中携带着龙火护符才能进入。', '你必須在一個團隊中，並在物品欄中攜帶著龍火護符才能進入。', 'Para entrar, debes formar parte de una banda, tener al menos nivel 50 y tener el Amuleto Pirodraco en tu inventario.', 'Debes ser parte de un grupo de banda, ser de nivel 50 como mínimo y tener el Amuleto Pirodraco en tu inventario para entrar.', 'Сюда допускаются только участники рейдовых групп, достигшие 50 уровня и владеющие амулетом Пламени дракона.'),
(2886, '공격대에 참여한 50 레벨 이상만 진입할 수 있습니다.', 'Vous devez faire partie d\'un groupe de raid et être au moins de niveau 50 pour entrer', 'Ihr müsst zu einer Schlachtgruppe gehören und mindestens Stufe 50 sein, um eintreten zu können.', '你必须在一个团队中，并且至少50级才能进入。', '你必須在一個團隊中，並且至少50級才能進入。', 'Para entrar, debes formar parte de una banda y tener al menos nivel 50.', 'Debes formar parte de una banda y tener al menos nivel 50 para entrar.', 'Сюда допускаются только участники рейдовых групп, достигшие 50 уровня.'),
(3133, '30 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 30 pour entrer.', 'Ihr müsst mindestens Stufe 30 sein, um eintreten zu können.', '只有至少30级的玩家才能进入。', '只有30級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 30.', 'Debes tener al menos nivel 30 para entrar.', 'Сюда допускаются только персонажи, достигшие 30 уровня.'),
(3134, '30 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 30 pour entrer.', 'Ihr müsst mindestens Stufe 30 sein, um eintreten zu können.', '只有至少30级的玩家才能进入。', '只有30級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 30.', 'Debes tener al menos nivel 30 para entrar.', 'Сюда допускаются только персонажи, достигшие 30 уровня.'),
(3183, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(3184, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(3185, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(3186, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(3187, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(3189, '45 레벨 이상만 진입할 수 있습니다.', 'Vous devez être au moins de niveau 45 pour entrer.', 'Ihr müsst mindestens Stufe 45 sein, um eintreten zu können.', '只有至少45级的玩家才能进入。', '只有45級以上的玩家才能進入。', 'Para entrar, debes tener al menos nivel 45.', 'Debes tener al menos nivel 45 para entrar.', 'Сюда допускаются только персонажи, достигшие 45 уровня.'),
(3528, '선행 퀘스트를 마치고 공격대에 참여해야만 진입할 수 있습니다.', 'Pour entrer, vous devez être en harmonie et dans un groupe de raid.', 'Ihr müsst abgestimmt sein und einer Schlachtgruppe angehören, um eintreten zu könnnen.', '你必须完成前置任务，并且在一个团队中才能进入。', '你一定要調整好並處於一個團隊隊伍才能進入。', 'Para entrar, debes estar armonizado y formar parte de una banda.', 'Debes estar armonizado y formar parte de una banda para entrar.', 'Сюда допускаются только подготовленные участники рейдовых групп.'),
(3669, '호드 일원만 진입할 수 있습니다.', 'Seule la Horde peut utiliser ce portail.', 'Nur die Horde kann dieses Portal benutzen.', '只有部落可以使用这个传送门。', '只有部落可以使用這個傳送門。', 'Solo la Horda puede utilizar este portal.', 'Solo la Horda puede utilizar este portal.', 'Этот портал открыт только для подданных Орды.'),
(3671, '얼라이언스 일원만 진입할 수 있습니다.', 'Seule l\'Alliance peut utiliser ce portail.', 'Nur die Allianz kann dieses Portal benutzen.', '只有联盟可以使用这个传送门。', '只有聯盟可以使用這個傳送門。', 'Solo la Alianza puede utilizar este portal.', 'Solo la Alianza puede utilizar este portal.', 'Этот портал открыт только для подданных Альянса.'),
(3726, '공격대에 참여한 50 레벨 이상만 진입할 수 있습니다.', 'Vous devez faire partie d\'un groupe de raid et être au moins de niveau 50 pour entrer', 'Ihr müsst zu einer Schlachtgruppe gehören und mindestens Stufe 50 sein, um eintreten zu können.', '你必须在一个团队中，并且至少50级才能进入。', '你必須在一個團隊中，並且至少50級才能進入。', 'Para entrar, debes formar parte de una banda y tener al menos nivel 50.', 'Debes formar parte de una banda y tener al menos nivel 50 para entrar.', 'Сюда допускаются только участники рейдовых групп, достигшие 50 уровня.'),
(3928, '공격대에 참여한 50 레벨 이상만 진입할 수 있습니다.', 'Vous devez faire partie d\'un groupe de raid et être au moins de niveau 50 pour entrer', 'Ihr müsst zu einer Schlachtgruppe gehören und mindestens Stufe 50 sein, um eintreten zu können.', '你必须在一个团队中，并且至少50级才能进入。', '你必須在一個團隊中，並且至少50級才能進入。', 'Para entrar, debes formar parte de una banda y tener al menos nivel 50.', 'Debes formar parte de una banda y tener al menos nivel 50 para entrar.', 'Сюда допускаются только участники рейдовых групп, достигшие 50 уровня.'),
(3948, '얼라이언스 일원만 진입할 수 있습니다.', 'Seule l\'Alliance peut utiliser ce portail.', 'Nur die Allianz kann dieses Portal benutzen.', '只有联盟可以使用这个传送门。', '只有聯盟可以使用這個傳送門。', 'Solo la Alianza puede utilizar este portal.', 'Solo la Alianza puede utilizar este portal.', 'Этот портал открыт только для подданных Альянса.'),
(3949, '호드 일원만 진입할 수 있습니다.', 'Seule la Horde peut utiliser ce portail.', 'Nur die Horde kann dieses Portal benutzen.', '只有部落可以使用这个传送门。', '只有部落可以使用這個傳送門。', 'Solo la Horda puede utilizar este portal.', 'Solo la Horda puede utilizar este portal.', 'Этот портал открыт только для подданных Орды.'),
(4008, '안퀴라즈 문이 열리기 전까지는 진입할 수 없습니다. 공격대에 참여한 50 레벨 이상만 진입할 수 있습니다.', 'Vous ne pouvez pas entrer ici tant que les portes d\'Ahn\'Qiraj ne sont pas ouvertes. Vous devez aussi être de niveau 50+ et dans un groupe de raid.', 'Die Tore von Ahn\'Qiraj müssen sich geöffnet haben, Ihr müsst Stufe 50+ sein und einer Schlachtgruppe angehören, um hier eintreten zu können.', '你无法进入这个区域，除非安其拉大门已经打开，并且你的等级不低于50级，同时你必须在一个团队中。', '除非安其拉之門被開啟，等級50級以上，並在團隊中的玩家才能進入。', 'No puedes entrar aquí a menos que las puertas de Ahn\'Qiraj estén abiertas, tengas nivel 50 o superior y formes parte de una banda.', 'No puedes entrar aquí a menos que las puertas de Ahn\'Qiraj se hayan abierto, seas de nivel 50 o superior y estés en un grupo de banda.', 'Сюда допускаются только участники рейдовых групп, достигшие 50 уровня. Врата Ан\'Киража должны быть открыты.'),
(4010, '안퀴라즈 문이 열리기 전까지는 진입할 수 없습니다. 공격대에 참여한 50 레벨 이상만 진입할 수 있습니다.', 'Vous ne pouvez pas entrer ici tant que les portes d\'Ahn\'Qiraj ne sont pas ouvertes. Vous devez aussi être de niveau 50+ et dans un groupe de raid.', 'Die Tore von Ahn\'Qiraj müssen sich geöffnet haben, Ihr müsst Stufe 50+ sein und einer Schlachtgruppe angehören, um hier eintreten zu können.', '你无法进入这个区域，除非安其拉大门已经打开，并且你的等级不低于50级，同时你必须在一个团队中。', '除非安其拉之門被開啟，等級50級以上，並在團隊中的玩家才能進入。', 'No puedes entrar aquí a menos que las puertas de Ahn\'Qiraj estén abiertas, tengas nivel 50 o superior y formes parte de una banda.', 'No puedes entrar aquí a menos que las puertas de Ahn\'Qiraj se hayan abierto, seas de nivel 50 o superior y estés en un grupo de banda.', 'Сюда допускаются только участники рейдовых групп, достигшие 50 уровня. Врата Ан\'Киража должны быть открыты.'),
(4055, '낙스라마스 선행 퀘스트를 마치고 공격대에 참여한 51 레벨 이상만 진입할 수 있습니다.', 'Pour entrer, vous devez être de niveau 51+, dans un groupe de raid, et être harmonisé à Naxxramas.', 'Ihr müsst Stufe 51+ sein, einer Schlachtgruppe angehören und die Abstimmung abgeschlossen haben, um Naxxramas betreten zu können.', '你必须在一个团队中，至少51级，并且完成了前置任务之后才能进入纳克萨玛斯。', '你必須為51級以上的玩家，處於團隊中，並達到進入納克薩瑪斯的條件。', 'Para entrar, debes tener nivel 51 o superior, formar parte de una banda y haber completado la Armonización.', 'Debes tener nivel 51 o superior, formar parte de una banda y estar armonizado con Naxxramas para entrar.', 'Сюда допускаются только участники рейдовых групп, достигшие 51 уровня и готовые к посещению Наксрамаса.');


-- End of migration.
END IF;
END??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
