#ifndef _PLAYERBOTS_CONFIG_H
#define _PLAYERBOTS_CONFIG_H

enum PlayerBotAutoEquip
{
    PLAYER_BOT_AUTO_EQUIP_STARTING_GEAR = 0,
    PLAYER_BOT_AUTO_EQUIP_RANDOM_GEAR = 1,
    PLAYER_BOT_AUTO_EQUIP_PREMADE_GEAR = 2,
};

#endif // _PLAYERBOTS_CONFIG_H
