# Disable known noisy warnings in Visual Studio and add /MP.
set(MSVC_DISABLED_WARNINGS "/wd4355 /wd4244 /wd4985 /wd4267 /wd4800")
set(MSVC_ADDITIONAL_FLAGS "/MP /permissive- /Zc:strictStrings")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${MSVC_DISABLED_WARNINGS} ${MSVC_ADDITIONAL_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${MSVC_DISABLED_WARNINGS} ${MSVC_ADDITIONAL_FLAGS}")
